### ISSUE TITLE
OJC

### ISSUE THREAD

**Issue by nu8** [simdjson/simdjson#1023]
Supposedly OJC is faster than SIMDJSON:

https://github.com/ohler55/ojc#benchmarks

but they dont offer any numbers to back that up, and now the creator is touting
that unfounded claim in other places:

https://github.com/ohler55/ojg/blob/master/design.md

since they dont have a benchmark, I though it might be helpful if OJC was
included in the benchmarks here.

**Comment by nu8** [comment]
Update, test here:

https://github.com/ohler55/ojc/tree/master/test/simdbench

**Comment by jkeiser** [comment]
Neat! I haven't read through ojc's code and docs, but I'll be interested to see what he is doing. I didn't look at the benchmark long, but one thing seems to be wrong: he's not passing a padded buffer, which is a requirement for simdjson. That will cause an allocation and memcpy every time parse is calling, which could account for the difference in performance.

**Comment by jkeiser** [comment]
We also run something like 2x slower on his test file than we do on most other example files, for some reason. Not sure why.

**Comment by plokhotnyuk** [comment]
Could it be because the message length is ~200 bytes?

**Comment by jkeiser** [comment]
Using a padded_string, it's about 20% faster. Not enough by itself to account for the difference. Could be ojc is faster on that file, which if it has full validation and actually parses a full tree, would be pretty surprising to me, even if it turns out to be a worst-case file for simdjson. (I expect simdjson's worst case to be better than, or at least as fast as, the fastest other parser out there.

I'd check if it does full JSON and UTF-8 validation, though, and I'd like to know whether it fully parses the JSON (escaping strings, converting to double and int) or whether it delays that step until later..

**Comment by jkeiser** [comment]
> Could it be because the message length is ~200 bytes?

It shouldn't be. We've done tests on large and small files both, and simdjson is fast at all scales.

**Comment by jkeiser** [comment]
And while it would also be interesting to see how OJC compares on the other files in jsonexamples, the JSON example they are using seems perfectly reasonable to me at first glance.

**Comment by plokhotnyuk** [comment]
Jsoniter-scala can parse this message at 630Mb/s speed from byte array with JSON representation in UTF-8 to [user's data structure](https://github.com/plokhotnyuk/jsoniter-scala/commit/32af9d2a99589706cb08dbb5ea1830317766d450#diff-a303b4693771dae62421c31c2940a704R12) where all fields are fully parsed and can be accessed just by one `MOV` instruction each in any order on Intel® Core™ i9-9880H CPU @ 2.3GHz (max 4.8GHz) with OpenJDK 16:

![image](https://user-images.githubusercontent.com/890289/86538499-a48a9800-bef6-11ea-998b-0d9c4a9d676c.png)

**Comment by nu8** [comment]
With all due respect, what does jsoniter-scala have to do with this issue? This issue isnt, and never was about some Java project.

**Comment by plokhotnyuk** [comment]
It can give you an idea that [testing outputs of competitors](https://github.com/plokhotnyuk/jsoniter-scala/tree/master/jsoniter-scala-benchmark/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark) before benchmarking can bring more trust to results.

**Comment by nu8** [comment]
Youve linked to a seemingly random folder of Scala files. I ask again, what does any of what youve said have to do with the difference between SIMDJSON and OJC?

**Comment by nu8** [comment]
Looks like the OJC result are not reproducible, with many seeing SIMDJSON as faster on the same test:

https://news.ycombinator.com/item?id=23739252

**Comment by jkeiser** [comment]
Looks like it was being compiled without -O3.

**Comment by lemire** [comment]
If someone is willing to add this parser to our benchmarks and to assess it with respect to standard compliance, please do so. Otherwise, if nobody is willing to do the leg work, I will eventually close this issue.

Regarding parsers in other programming languages (Rust, Swift, Go, Scala, Java, D...), we decided some time ago not to include them in the core simdjson library benchmarks. There are many JSON benchmarks out there, some of them quite broad. We focus on C++. It is not because we do not like scala, Go, Rust... it is because simdjson is a C++ project. Furthermore, anyone can build a benchmark, and we encourage it. 

When we omit another parser, we do not, in any way, mean to look down on it. Our main focus in the core simdjson repository is to work on simdjson. It is useful to compare against alternatives, but that's hardly our main activity.  As for myself, I take RapidJSON as the gold standard of C++ parsers. It is fully standard compliant, and super fast. So I primarily compare simdjson against RapidJSON.

**Comment by lemire** [comment]
We had a real performance problem on tiny files... an overhead of about 100 ns due to runtime dispatching being effectively broken (the runtime dispatching would be computed with each query).

See https://github.com/simdjson/simdjson/pull/1048

**Comment by lemire** [comment]
I am going to be closing this issue only someone prepares a pull request in the near future.

**Comment by jkeiser** [comment]
Oh we determined the claim was not true.

**Comment by jkeiser** [comment]
More specifically, the author had mistakenly compiled simdjson with optimizations off.
