### ISSUE TITLE
JSONPointer does not follow RFC6901 it follows the Relative JSON Pointers specification (documentation bug)

### ISSUE THREAD

**Issue by bbulkow** [simdjson/simdjson#1063]
Your support of JSONPointer ( RFC6901 ) seems to be in error. 

The RFC specifically states the search string must begin with '/'. There's a reason: the empty string ("") refers to the entire document, the string "/" refers to a field with name "" in the root of the document. This is all covered in the RFC.

This code succeeds and should fail:
```
	string test_str("{\"id\": 100}");
	try {
		simdjson::dom::parser test_parser;
		simdjson::dom::element test_element = test_parser.parse(test_str);
		 cout << test_element.at("id") << endl;
	}
```
This code fails and should succeed:
```
	string test_str("{\"id\": 100}");
	try {
		simdjson::dom::parser test_parser;
		simdjson::dom::element test_element = test_parser.parse(test_str);
		 cout << test_element.at("/id") << endl;
	}
```

I know you might have trouble changing the API at this point, but if you could have a note if your non-standard implementation, and/or a function which is compliant, that would be super cool.

**Comment by lemire** [comment]
This is indeed looks like a bug. I don't understand.

Marked for milestone 0.5.

cc @jkeiser

**Comment by lemire** [comment]
I'd like to thank you for your report.

**Comment by jkeiser** [comment]
You're absolutely right. For historical information, element.at() essentially implements Relative JSON Pointers (https://tools.ietf.org/id/draft-handrews-relative-json-pointer-00.html), because the element object could be any value in the document. JSON Pointer only specifies what happens when you have a reference to the document itself. I think there's probably still a difference with empty string (I wasn't specifically implementing that spec, just trying to make something that worked well for relative elements).

I believe this got lost when we changed parse() to return element instead of document (document had the document-level pointer stuff, IIRC).

I don't know the exact right answer offhand here; I think we want at() on a value to implement a relative pointer, but we *definitely* also want a real JSON Pointer implementation.

**Comment by lemire** [comment]
@jkeiser Thank you John for the comment. Very helpful.

Let us find a way to fix this, somehow, for 0.5.

**Comment by bbulkow** [comment]
Wonderful. The history makes sense. 

I would vote for a different interface. Having an implementation of Relative JSON Pointers for inside the document makes sense.

And, FYI, I did a test against RapidJSON for the same use case ( I have about 200k JSON objects in my test set, etc ) and the difference was about 7x faster for SIMDjson.

**Comment by lemire** [comment]
@bbulkow I very much appreciate the feedback.

**Comment by lemire** [comment]
I have updated the title to point out that it is not a software bug per se, but rather a documentation bug. We say that we support X and provide Y instead. It is genuine and serious issue, but not the same as faulty software.

**Comment by bbulkow** [comment]
I guess you have to remove all the references to supporting JSONPointer, and update with the syntax you do support. Sure, documentation.

**Comment by lemire** [comment]
> I guess you have to remove all the references to supporting JSONPointer, and update with the syntax you do support. Sure, documentation.

I think that's the minimum we need to do to fix this issue/bug.

**Comment by lemire** [comment]
@bbulkow @jkeiser I looked at this and I don't think that what we support is relative JSON pointers.

We really do support JSON pointers, but a lenient version of it which allows you (intuitively) to access relative paths and to omit the leading "/".

You'd think that relative JSON pointers would be that, but it is not. The  relative JSON pointer spec looks to be something else entirely.

Anyhow, our support for true JSON pointers was, unfortunately, broken accidentally (though not fundamentally, the underlying code is fine, but some glue was missing). It will be restored in the next release. We now have better tests.

**Comment by bbulkow** [comment]
I take you to say it's a bug not a feature? In that I tried the strings in the RFC and they didn't work, so in the next release it'll be working again, and the strings in the RFC will work?

**Comment by lemire** [comment]
> I take you to say it's a bug not a feature? In that I tried the strings in the RFC and they didn't work, so in the next release it'll be working again, and the strings in the RFC will work?

Yes. They will work again.


What the new code would do is that it would take "/something/something" and parse that as "[empty string]/something/something". So you could not use them as JSON Pointer. 

Now you could say "just omit the leading '/'" and, indeed, it may work, but then there is not specification for that. It is not, as far as I can tell, what relative JSON pointers are.

You can see that all the tests from the RFC are there:

https://github.com/simdjson/simdjson/pull/1064

If you look at the code changes, they are tiny. Well, I passed all of the string_view instances by value instead of by reference, but this is just me fixing "en passant" a slightly design issue.

If you'd like to contribute additional tests, please do so. I'd be glad to add them.

This will be in 0.5.

**Comment by bbulkow** [comment]
Yes, I agree. Leaving off the / was not a relative JSON pointer. Thanks for the fix.

**Comment by lemire** [comment]
@bbulkow 

Let me try to be clearer. Here is what I think happened.

We implemented RFC6901.

Then @jkeiser redesigned the API and decided (in a perfectly reasonable manner), that the path should be relative. What he did was perfectly fine logically... *but* it got us outside of the specification. Of any specification.


So now, what I am trying to do is hit somewhere in the middle... Allow the true JSON Pointer spec to work... but also support what @jkeiser wanted to do.


I'll wait for @jkeiser to review what I did... but I expect that I am essentially correct and my retelling of the story.

Now, for me, the important short term is to get back a spec., and the only one that makes sense to me is RFC6901. So we should support that fully. 

The RFC6901  specification allows to deal with "error handling" as we see fit. This means that once you write that path that is not part of RFC6901, then we can do whatever we want, which is where we can accommodate (the perfectly reasonable) approach that @jkeiser wanted.

In due time, we should documented better how we do it.

**Comment by lemire** [comment]
Here is the idea:

```c++
auto cars_json = R"( [
  { "make": "Toyota", "model": "Camry",  "year": 2018, "tire_pressure": [ 40.1, 39.9, 37.7, 40.4 ] },
  { "make": "Kia",    "model": "Soul",   "year": 2012, "tire_pressure": [ 30.1, 31.0, 28.6, 28.7 ] },
  { "make": "Toyota", "model": "Tercel", "year": 1999, "tire_pressure": [ 29.8, 30.0, 30.2, 30.5 ] }
] )"_padded;
dom::parser parser;
dom::element cars = parser.parse(cars_json);
cout << cars.at("/0/tire_pressure/1") << endl; // Prints 39.9
cout << cars.at("0/tire_pressure/1") << endl; // Prints 39.9
for (dom::element car_element : cars) {
    dom::object car;
    simdjson::error_code error;
    if ((error = car_element.get(car))) { std::cerr << error << std::endl; return false; }
    double x = car.at("tire_pressure/1");
    cout << x << endl; // Prints 39.9, 31 and 30
}
```

**Comment by lemire** [comment]
I have tweaked the implementation. What I have now is simpler. It is all JSON Paths as per the specification. However, if you call a JSON path of a node, the node acts as if it were a whole JSON document.

I bet that it is what @jkeiser had in mind.

It won't do to omit the leading '/' as it gets us into a messy syntax. Let us stick with the RFC.

**Comment by jkeiser** [comment]
@lemire Holy crap, I totally read that spec wrong. [Relative JSON Pointers](https://tools.ietf.org/id/draft-handrews-relative-json-pointer-00.html#rfc.section.5.1) really clashes with intuition. Historically, I was trying to make something that would work nicely with operator[], which means object["key"] in particular needs to work and be relative :) (At least one other major library does this as well, but I can't recall or find which one right now.) I'd almost rather not implement Relative JSON Pointers, period, but that's a story for another day :)

I am all for fixing this. However, I think we should either make `at()` private on everything except document (remove it from the public API) rather than make `/` mean "current node." Everything else in the world (e.g. [XPath](https://www.w3.org/TR/xpath-31/#id-path-expressions) and directory trees) treat `/` as "go back to the root," which means most peoples' intuitions will too. While we can decide to break that intuition, I don't think we should do it without a great deal of consideration :)

**Comment by lemire** [comment]
@jkeiser 

1. We can simply "not document" the other uses of JSON Pointers. If it is not documented, then it is not officially supported. 

2. "At least one other major library does this as well" => It is really best to refer to a specification. If there are implementations, and we follow it, then maybe we should write up the specification. But this involves making sure we think through the issues.

3. "Everything else in the world (e.g. XPath and directory trees) treat / as "go back to the root," which means most peoples' intuitions will too." 

=>

Let us not get confused here by drawing analogies with things that are not quite comparable.

A. In XML, an XML name cannot be empty nor can it contain the slash character.

B. In most OSes, the empty string cannot be the name of a directory or file. The separator (e.g., /) also cannot be used within a string.


Not so in JSON. The slash itself is allowed inside a key. And even the empty string is a valid key. So we can't just take things that worked in XML and apply them as is in JSON.

I think that JSON Pointer solves the "/" thing by forcing it to have it escaped. That is good. However, the empty string remains. 

And empty strings are not a corner case. I bet that they appear in the wild.


3. We could allow for non-root nodes the syntax "me/ma/mo", but the problem you have is that the empty string is a perfectly valid key. So "/ma/mo" has to be interpreted as "(empty string)/ma/mo" and... well... you see the problem... if you insist that "/" is the root node, how do you distinguish between "(empty string)/" and "(nothing)/"?

4. My proposal is to apply RFC6901 on nodes by interpreting nodes as their own JSON documents. I think it is consistent. But I'll be very happy not to publish it.

**Comment by jkeiser** [comment]
@lemire the empty string case is very real, and a complication for user intuition. Heck, I'm pretty sure I am the one that added a bunch of tests for nodes with empty keys :) User intuition doesn't take any of that into account, and for the library designer, that is important.

There are other ways to skin that cat, though. Documenting the weird case of empty string seems important either way. We could, for example, support the current relative JSON Pointer implementation (and user intuition) but warn users that while `/` is generally optional, to index a path with an empty string at the front you will have to use `//`.

Probably better: use `.at_pointer()` instead of `.at()`, reserving the shorter word for something more intuitionistic later. That way we don't rule out Relative JSON Pointers by stuffing my hastily-thought-out relative implementation into it, either.

However, none of that should block fixing the fact that JSON Pointer doesn't work, and I'll accept the breaking change to buy that :) I think I can live with `/` having JSON Pointer meaning "current node is a document" anywhere in the tree. I'd live with it even better if it was called at_pointer, though! :)

**Comment by lemire** [comment]
@jkeiser The PR has been updated. It maintains the current "at" but deprecated it, and refers the user to "at_pointer" for standard compliance. The old code should still work, without the leading "/".

We don't have to deprecate it, but I think it makes sense to entice users to go for standard compliance.

**Comment by lemire** [comment]
@bbulkow The issue has been fixed in our main branch. You need to use `at_pointer` if you want to have the RFC. We preserved the old behaviour of `at` because breaking code is something we want to avoid.

Thanks for your report.

**Comment by wanweiqiangintel** [comment]
Hi, @lemire, in my practice, I find some interesting cases.
If there is a key begin with "/" in the json like {"/key1":"value1", "/key2":"value2"}, how can we use at_pointer() to locate value? I am not sure that the current function at_pointer() supports this case.
