### ISSUE TITLE
Kostya Benchmarks claim 3 JSON parsers are faster (on this one specific synthetic benchmark ill-suited for DOM support)

### ISSUE THREAD

**Issue by TkTech** [simdjson/simdjson#1111]
The [Kostya JSON benchmarks](https://github.com/kostya/benchmarks#json) claim that 3 parsers are faster than simdjson.
For typed JSON, this might actually be true, since for example C++ DAW uses a number of tricks to speed up when the JSON file is laid out exactly the same as the structure it's loading into. If there's any deviation speed drops drastically.

However, it's very unlikely that serde custom is actually faster than simdjson under any condition. Especially considering serde's own benchmarks show simdjson is [significantly](https://github.com/serde-rs/json-benchmark) faster.

Kostya's benchmarks are being referenced by Nim for choosing a new JSON parser for the language in https://github.com/nim-lang/RFCs/issues/188.

**Comment by lemire** [comment]
Is this an issue we need to track?

**Comment by TkTech** [comment]
I would say so, if only because of the claims in the README to be "2.5x faster than anything else out there", and "simdjson is the first fully-validating JSON parser to run at gigabytes per second (GB/s) on commodity processors". In my opinion, making these claims means defending them when necessary.

**Comment by jkeiser** [comment]
It's a nice benchmark in general. I haven't looked at the competing examples yet. I like the fact that it actually *uses* the results of the parse. It looks like they include `-O3 -Wall -flto` in their compile, too, which I think is the correct level of optimization, yes? I am curious what architecture they are running on (but not THAT curious, we're damn fast all the way down to fallback).

The two things that stand out to me are:

* The test uses error codes in one part, and exceptions in the other. Exceptions and error chaining are both perfectly reasonable, but it'd be nice to get it in one form or the other--either we're going for maximum readability, or maximum explicitness (and possibly performance).
* The [way they get x, y and z](https://github.com/kostya/benchmarks/blob/master/json/test_simdjson.cpp#L53-L60) from the point isn't as performant as it could be because we start at the beginning of the object each time. We do a total of 6 string comparisons per object (x once, y twice and z three times). I don't think their method is unreasonable, though--it's what I would write.

If it's true that something like typed JSON is faster, on-demand parsing will address the issue, I imagine.

**Comment by jkeiser** [comment]
Speed is our differentiating feature. I wouldn't mind following up on this sort of thing in general, at *least* to get an idea of places we might be slow. It's also worth following up on large public benchmarks or benchmarks being used for major projects, and make sure the tests represent us fairly, since that's a pretty big inroad to users. I don't know if nim is a big project with a lot of attention or not, but I do know I've heard of it (which might just because I follow reddit.com/r/ProgrammingLanguages).

**Comment by lemire** [comment]
I have documented this "Parse big json file" benchmark before. It is addressed by multiple issues:

1. [Add optimization for large files (far exceeding a page)](https://github.com/simdjson/simdjson/issues/177)
2. [Scan input (stage 1) in fixed-size batches](https://github.com/simdjson/simdjson/issues/670)
3. [comparison: `GDC fast` 2X faster according to https://github.com/kostya/benchmarks#json](https://github.com/simdjson/simdjson/issues/482)

Pay attention to the 3rd issue, it is the same as the one that is being raised here.

Let me elaborate once more... I am going to repeat myself, but I just want to be clear...

When benchmarking, it is important to compare comparable approaches. What simdjson does currently is to take the input, process and validate it all, and generate a DOM tree. Then it gives you access to the DOM tree. And we make no assumption about the content of the JSON.

Let us consider the benchmark that preoccupies you. 



Firstly,  it is all float parsing. So it is a case where it is difficult for one parser to be much faster because float parsing is a bitch. The simdjson library offers exact parsing. What do the other parsers offer? Well, RapidJSON is used in its default mode which means that it does fast approximate float parsing. What about daw::json? [Well check it out for yourself](https://github.com/beached/daw_json_link/blob/release/include/daw/json/impl/daw_json_parse_real.h)... (it is approximate fast parsing.) But anyhow: on such a benchmark, nobody is going to hit gigabytes per second because nobody knows how to parse floating-point numbers exactly, with all the right rounding, at gigabytes per second. So there is no way for this benchmark to challenge our claim that simdjson is the first standard compliant to hit gigabytes per second: it is understood and thoroughly documented (and has been documented for a long time) that we can't promise gigabytes per second on floating-point tests. (It turns out that this is a secondary issue. Read on.)

Secondly, it is a scenario where the structure is known to the programmer. That's not unrealistic, but it is something that simdjson does not do right now. It looks like the daw::json uses this knowledge to materialize directly something in the right formart (https://github.com/kostya/benchmarks/blob/master/json/test_dawjsonlink.cpp). Other libraries that do well on this benchmark also relies on their compile-time knowledge. This is important in the context where we are dealing with large data volumes, see my third point. (I am *not* pissing on daw::json. It looks great.) But note how this is not something simdjson does at all: we have no support currently for this kind of application. So you are comparing different designs, different problems, entirely.

Thirdly, the input is a large file. It is difficult to allocate memory generally at high speed. In fact, it can take longer to allocate memory than it could take to parse the equivalent volume in JSON. The benchmark is specific. It is not a scenario where you get to reuse the memory allocated. So you pay dearly for the memory usage. See this blog post...
https://lemire.me/blog/2020/01/14/how-fast-can-you-allocate-a-large-block-of-memory-in-c/

If you benchmark simdjson, you will find that it is entirely stalled. It is waiting for memory access. Our performance documentation offers all the tips and tricks...

https://github.com/simdjson/simdjson/blob/master/doc/performance.md


So ...

1. Reuse the parser.
2. If you are going to work with large files, then use huge pages or transparent large pages.


If you do follow our guidelines, you will find that we are very fast. Yes, even on this benchmark we can be really fast with transparent huge pages and parser reuse. Of course, if you do not follow our recommended usage, then we are not going to shine. That's because it has a lot of allocation to do... Allocate the DOM, then allocate the data storage for the final structure. Say you allocate data at 3 GB/s... if you need to allocate 3x or 4x the size of the original JSON file... how fast do you think you can go in the end? Right. So your system is going to be spending all its time creating pages, page walking and the like.


Now. Can we do better on this particular benchmark without the need for performance guidelines and will we? Absolutely. But there is no (new) issue there per se. It is simply a usage that simdjson does not currently support (small pages, large files, structure known at compile time). It is part of our roadmap toward 1.0 to upgrade simdjson and @jkeiser has specifically been quite busy with relevant issues.

I expect that by 0.6, you will see great progress with respect to this issue. We should be able to close the gap on this particular benchmark.

**Comment by andyzimmerer** [comment]
Trank you

**Comment by jkeiser** [comment]
I couldn't find an explanation of energy in there--i.e. why is simdjson so much more energy efficient, even though other implementations are close to the same speed?

**Comment by pauldreik** [comment]
Interesting observation. Is it perhaps related to "branchiness"? I know a significant part of the cpu is related to branch prediction, and perhaps that does not need to work as much as for the other implementations?

**Comment by lemire** [comment]
Here are the current numbers (October 16, 2020):



|                        Language |       Time, s |     Memory, MiB |        Energy, J |
| :------------------------------ | ------------: | --------------: | ---------------: |
|    C++/g++ (simdjson On-Demand) |  0.10 ± 00.00 |  169.45 ± 00.17 |     1.58 ± 00.07 |
|                    D/gdc (fast) |  0.10 ± 00.01 |  231.34 ± 00.32 |     2.60 ± 00.27 |
|         C++/g++ (DAW JSON Link) |  0.11 ± 00.00 |  109.23 ± 00.05 |     2.42 ± 00.29 |
|             Rust (Serde Custom) |  0.15 ± 00.01 |  108.47 ± 00.08 |     2.79 ± 00.29 |
|              Rust (Serde Typed) |  0.15 ± 00.01 |  120.19 ± 00.20 |     2.89 ± 00.30 |
|                 C++/g++ (gason) |  0.17 ± 00.01 |  206.35 ± 00.06 |     3.71 ± 00.47 |
|          C++/g++ (simdjson DOM) |  0.17 ± 00.00 |  286.23 ± 00.49 |     3.39 ± 00.15 |
|             C++/g++ (RapidJSON) |  0.22 ± 00.01 |  238.14 ± 00.09 |     4.81 ± 00.62 |
|                            Java |  0.54 ± 00.02 |  327.50 ± 01.47 |    14.71 ± 00.99 |
|         C++/g++ (RapidJSON SAX) |  0.55 ± 00.03 |  109.43 ± 00.05 |    11.62 ± 01.33 |
|                           Scala |  0.61 ± 00.03 |  396.98 ± 06.37 |    15.99 ± 01.23 |
|                         Node.js |  0.68 ± 00.03 |  430.79 ± 00.33 |    16.22 ± 01.38 |
|                   Go (jsoniter) |  0.70 ± 00.02 |  238.82 ± 00.28 |    14.71 ± 00.89 |
|                Crystal (Schema) |  0.80 ± 00.03 |  157.29 ± 00.13 |    15.40 ± 01.30 |
|                     Python/pypy |  0.81 ± 00.04 |  405.43 ± 00.23 |    18.73 ± 02.35 |
|                  Crystal (Pull) |  0.84 ± 00.06 |  128.56 ± 00.06 |    15.19 ± 02.57 |
|                   Julia (JSON3) |  0.87 ± 00.05 |  614.24 ± 20.45 |    18.60 ± 02.46 |
|            Rust (Serde Untyped) |  0.94 ± 00.03 |  948.43 ± 00.11 |    18.88 ± 01.59 |
|         Perl (Cpanel::JSON::XS) |  0.99 ± 00.04 |  524.43 ± 00.07 |    20.01 ± 01.90 |
|                         Crystal |  1.08 ± 00.06 |  503.70 ± 00.08 |    21.97 ± 02.43 |
|                              Go |  1.12 ± 00.05 |  209.46 ± 00.32 |    23.88 ± 02.19 |
|                             PHP |  1.23 ± 00.05 |  803.52 ± 00.14 |    26.92 ± 02.28 |
|                           V/gcc |  1.42 ± 00.07 |  591.91 ± 00.09 |    30.57 ± 02.98 |
|                         V/clang |  1.43 ± 00.05 |  592.41 ± 00.08 |    31.70 ± 02.42 |
|                        Go/gccgo |  1.48 ± 00.08 |  232.10 ± 05.87 |    29.91 ± 03.45 |
|            Nim/gcc (Packedjson) |  1.49 ± 00.07 |  399.36 ± 00.06 |    30.95 ± 03.50 |
|                C++/g++ (json-c) |  1.52 ± 00.06 | 1325.49 ± 00.07 |    33.63 ± 03.74 |
|          Nim/clang (Packedjson) |  1.53 ± 00.07 |  399.85 ± 00.05 |    31.72 ± 03.71 |
|                         Clojure |  1.61 ± 00.08 | 1020.39 ± 16.00 |    41.27 ± 02.62 |
|             CPython (UltraJSON) |  1.68 ± 00.05 |  662.54 ± 02.86 |    36.56 ± 01.47 |
|                         Haskell |  1.77 ± 00.10 |   10.34 ± 00.48 |    37.49 ± 04.16 |
|                          Python |  1.77 ± 00.06 |  493.07 ± 00.07 |    39.60 ± 02.51 |
|                         Nim/gcc |  1.88 ± 00.09 |  904.85 ± 00.13 |    38.09 ± 03.77 |
|                       Nim/clang |  1.94 ± 00.08 |  905.25 ± 00.13 |    37.82 ± 03.93 |
|                    C#/.NET Core |  2.01 ± 00.12 |  761.27 ± 00.11 |    44.82 ± 04.74 |
|                         C#/Mono |  2.16 ± 00.08 |  462.55 ± 00.15 |    43.34 ± 04.34 |
|                            Ruby |  2.28 ± 00.08 |  385.94 ± 16.27 |    45.44 ± 04.11 |
|                     Ruby (YAJL) |  2.28 ± 00.10 |  408.90 ± 00.18 |    45.57 ± 04.76 |
|                    Ruby (--jit) |  2.29 ± 00.08 |  395.60 ± 09.99 |    49.10 ± 05.21 |
|                           D/gdc |  2.30 ± 00.12 |  713.56 ± 00.07 |    44.22 ± 05.66 |
|                          D/ldc2 |  2.57 ± 00.05 |  789.58 ± 00.12 |    52.42 ± 02.35 |
|                       Rust (jq) |  3.90 ± 00.16 |  886.10 ± 00.75 |    76.39 ± 16.94 |
|                      Ruby/jruby |  3.92 ± 00.18 | 1964.91 ± 39.23 |   112.52 ± 05.56 |
|                 C++/g++ (Boost) |  4.11 ± 00.19 | 1549.66 ± 00.05 |    82.61 ± 09.84 |
|                           D/dmd |  5.03 ± 00.10 |  790.35 ± 00.06 |    99.09 ± 04.89 |
| C#/.NET Core (System.Text.Json) |  6.95 ± 00.26 |  646.91 ± 00.12 |   155.61 ± 11.91 |
|               Perl (JSON::Tiny) | 11.98 ± 00.38 |  647.40 ± 00.10 |   234.12 ± 21.39 |
|        Ruby/truffleruby (--jvm) | 23.63 ± 01.31 | 2141.52 ± 71.40 |   632.38 ± 73.35 |
|                Ruby/truffleruby | 66.10 ± 02.02 | 2902.65 ± 52.00 | 1385.38 ± 112.06 |


The lesson here, folks, is that Ruby is slow.

**Comment by lemire** [comment]
Given that, at least at the moment, we are at the top of the chart, I am going to close this issue. 

I am sure that this one external benchmark will provide different results over time. If we fall off down drastically on some benchmark and you think that there is an issue that needs to be resolved, please reopen a new issue.
