### ISSUE TITLE
Clarify in documentation how padding is needed

### ISSUE THREAD

**Issue by pauldreik** [simdjson/simdjson#1178]
In PR #1163, a discussion ensued about padding. By default, padding is not needed. The documentation claims it is. Either the defaults should change, or the documentation. Maybe both :-)

From the discussion in #1163:

Speaking about example code that should be correct. Here is a mention of parse() which does not seem to respect the padding:

https://github.com/simdjson/simdjson/blob/33c97452012f7ba05812b33250281856f4f14de6/singleheader/simdjson.h#L2071-L2081

The doxygen document says padding is mandatory: 
https://github.com/simdjson/simdjson/blame/master/doc/basics_doxygen.md#L87-L88

...but the "mystery" is resolved further down in simdjson.h:

https://github.com/simdjson/simdjson/blob/7fc07e2d5ea57ceb0c8f99aa2ac205004d0d7ef3/singleheader/simdjson.h#L3402-L3408

I think this documentation string is confusing. The reason one does not have to think about padding is because the last parameter realloc_if_needed defaults to true.  I also believe that the text about the extra bytes being allocated is necessary but not have to be initialized is not true - reading from uninitialized data is undefined behaviour in C++.

May I suggest the following changes:

In [simdjson.h](https://github.com/simdjson/simdjson/blob/7fc07e2d5ea57ceb0c8f99aa2ac205004d0d7ef3/singleheader/simdjson.h#L3402-L3408) (I mean changing the underlying header before amalgamization):
```
### Buffer Padding
   *
   * If the realloc_if_needed is set to true (the default), the incoming buffer does not have to be
   * padded. If realloc_if_needed is false, the buffer has to be padded with at least 
   * SIMDJSON_PADDING bytes at the end.
   * Supplying a padded buffer is more efficient, because it potentially avoids an extra copy
   * which is beneficial for performance.
```
Perhaps there are other reasons for being more efficient - I guess the handling of reading data into simd registers is easier if one does not have to worry about the end?

In [doc/basics_doxygen.md](https://github.com/simdjson/simdjson/blame/master/doc/basics_doxygen.md#L87-L88):
```
Json can be parsed by reading from a string:
std::string str("[1,2,3]");
parser.parse(str);
If the input is padded with at least SIMDJSON_PADDING bytes, the parser can work more
efficiently:
parser.parse("[1,2,3]"_padded);
```
I can imagine that having the input coming from a large string or vector of char, the fastest way would be to resize the string or vector in place rather than letting a copy be made internally. But that would not fit under the basics section, perhaps?

_Originally posted by @pauldreik in https://github.com/simdjson/simdjson/pull/1163#issuecomment-693597211_

**Comment by lemire** [comment]
> I also believe that the text about the extra bytes being allocated is necessary but not have to be initialized is not true - reading from uninitialized data is undefined behaviour in C++.


The documentation states "It does not matter what  those bytes are initialized to, as long as they are allocated."

How would you improve on this?

**Comment by lemire** [comment]
>  I guess the handling of reading data into simd registers is easier if one does not have to worry about the end?

I am not sure it is related to SIMD. I am pretty sure that our SIMD-intensive component (stage 1) does not require padding. The minifier and UTF-8 code do not require padding. The padding is primarily for stage 2 and it would be just as useful if we did not rely on SIMD.

The padding might be dropped in the future but there is some engineering needed before we get there.

**Comment by jkeiser** [comment]
@pauldreik [this comment](https://news.ycombinator.com/item?id=23742404) sums up one of the major ways we use the padding. In short, many loops go faster if we "overshoot" a little each time, because it's the same cost to load and process a bunch of bytes as it is to load and process one byte. We really do read the uninitialized memory and even write it out, but it never gets used anywhere because we cap the length to the valid bytes only.

**Comment by lemire** [comment]
@jkeiser The comment may suggest that it is about SIMD, but consider this code:
```C++
uint32_t str4ncmp(const uint8_t *src, const char* atom) {
  uint32_t srcval; // we want to avoid unaligned 32-bit loads (undefined in C/C++)
  static_assert(sizeof(uint32_t) <= SIMDJSON_PADDING, "SIMDJSON_PADDING must be larger than 4 bytes");
  std::memcpy(&srcval, src, sizeof(uint32_t));
  return srcval ^ string_to_uint32(atom);
}

simdjson_really_inline bool is_valid_true_atom(const uint8_t *src) {
  return (str4ncmp(src, "true") | is_not_structural_or_whitespace(src[4])) == 0;
}

```

It relies on padding, but there is no SIMD.

**Comment by jkeiser** [comment]
Yep, that's a good example too.

**Comment by pauldreik** [comment]
Thanks for the background. 

> The documentation states "It does not matter what those bytes are initialized to, as long as they are allocated."
> 
> How would you improve on this?

Perhaps: 
Simdjson will for efficiency read up to SIMDJSON_PADDING bytes after the supplied length. Those bytes should be initialized (the exact value is not important) to avoid undefined behaviour in C++. Leaving them uninitialized may cause warnings in a tool like valgrind, even if current compilers generates correct code also for uninitialized values.

**Comment by pauldreik** [comment]
Just a thought: would it be possible to add static asserts at the places padding is needed? That would make the code self explaining and ease up where to look in case one wants to change it. Like in the is_valid_true_atom example, which reads five bytes could use
```cpp
static_assert(SIMDJSON_PADDING>=5,"");
```

**Comment by lemire** [comment]
@pauldreik 

> would it be possible to add static asserts at the places padding is needed?

We do, as my example illustrates. If you have spotted some place where there is missing static_assert, please report it. It would be considered a bug.

**Comment by lemire** [comment]
> Simdjson will for efficiency read up to SIMDJSON_PADDING bytes after the supplied length. Those bytes should be initialized (the exact value is not important) to avoid undefined behaviour in C++. Leaving them uninitialized may cause warnings in a tool like valgrind, even if current compilers generates correct code also for uninitialized values.

The typical usage of simdjson is that you take a data pointer whose value is only known at runtime. (It is possible to compile simdjson so that it processes a fixed block of data known at compile time, but that's not what this particular documentation is for since there is no cause for pointer passing then, use padded_string instances instead.) The code generation (at the level of simdjson) with respect to how the data is read is fixed at compile time, and is strictly the same, whether you pass a pointer to garbage memory or to a fine memory region. It is all runtime behavior. So I think that the risk that the compiler might misbehave from our point of view because it spots undefined behavior is a red herring, at least as far as our users are concerned. That is, it is not actually possible. That's not what you wrote nor what you meant, but look at it from the point of view of Joe the programmer. He reads this and comes away with the impression that simdjson relies or undefined behavior that may very well break when a new compiler comes out. You know what Joe the programmer does? He tells his boss and friends that simdjson is unsafe. And we cannot even blame Joe, because it is right there, in our documentation: we said that if Joe is not very careful, the compiler might play tricks with him... it just so happen that the current compilers do not. Not very reassuring, is it ? Well, I would say that we have just mislead Joe.

I submit to you that what is a lot more useful to Joe is to explain to him what must be done, providing as needed safe examples.

How the API is designed is important here. For Joe to get in trouble, Joe has to provide raw data pointers (something we definitively do not put front and center), but he also has to specifically request that the data is not copied (which is otherwise the default). For that, Joe needs to dig deep in our documentation where it will be clear that this is done for padding purposes. Of course, at that point, Joe can go our of his way and not pad properly and so forth... But that becomes increasingly unlikely.

I feel that this part of the library has already good layers of protection for the users and for users. I am always eager to improve the documentation, but I think that the documentation needs to be actionable rather than scary.

**Comment by pauldreik** [comment]
What remains in this ticket: see what is left actionable now when https://github.com/simdjson/simdjson/commit/f410213003b378d6f7edf17a9a44c94e75bc36ba is merged.

**Comment by pauldreik** [comment]
I think this is fine for now.
