### ISSUE TITLE
Question / Documentation: Is there any facility to read/write json files stored in memory or accessed via callbacks? 

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [simdjson/simdjson#1218]
Hi, we're trying to use this in our game engine/framework, for obvious reasons we have our own file handling API (systems that don't let you just "access" files, files that don't exist/are virtual, files in zip and similar archives, networked resources).

This probably touches on #1020 and #31

Basically my API gives access to a `fread` and `fwrite` like methods on a File interface, how could I tie this into simdjson so I don't "just give you the filename" ?

CC: @AnastaZIuk

**Comment by TkTech** [comment]
simdjson works on complete files, rather than streaming, so there's no point passing through a read or write method. Just read the file yourself and pass the contents to `Parser.parse()`,

**Comment by devshgraphicsprogramming** [comment]
You mean this method, right?
https://github.com/simdjson/simdjson/blob/a9480a768bd80174928fee25ecc33947faad4603/include/simdjson/dom/parser.h#L158

**Comment by lemire** [comment]
----
If you need a lower-level interface, you may call the function `parser.parse(const char * p, size_t l)` on a pointer `p` while specifying the length of your input `l` in bytes. To see how to get the very best performance from a low-level approach, you way want to read our [performance notes](https://github.com/simdjson/simdjson/blob/master/doc/performance.md#padding-and-temporary-copies) on this topic (see the Padding and Temporary Copies section)

Source: https://github.com/simdjson/simdjson/blob/master/doc/basics.md#the-basics-loading-and-parsing-json-documents



----

The simdjson function `parser.parse` reads data from a padded  buffer, containing SIMDJSON_PADDING extra bytes added at the end. If you are passing a `padded_string` to `parser.parse` or loading the JSON directly from
disk (`parser.load`), padding is automatically  handled.When calling `parser.parse` on a pointer (e.g., `parser.parse(my_char_pointer, my_length_in_bytes)`) a temporary copy  is made by default with adequate padding and you, again, do not need to be concerned with padding.

Some users may not be able use our `padded_string` class or to load the data directly from disk (`parser.load`). They may need to pass data pointers to the library.  If these users wish to avoid temporary copies and corresponding temporary memory allocations, they may want to call `parser.parse` with the `realloc_if_needed` parameter set to false (e.g., `parser.parse(my_char_pointer, my_length_in_bytes, false)`). In such cases, they need to ensure that there are at least SIMDJSON_PADDING extra bytes at the end that can be safely accessed and read. They do not need to initialize the padded bytes to any value in particular. The following example is safe:


```C++
const char *json      = R"({"key":"value"})";
const size_t json_len = std::strlen(json);
std::unique_ptr<char[]> padded_json_copy{new char[json_len + SIMDJSON_PADDING]};
memcpy(padded_json_copy.get(), json, json_len);
memset(padded_json_copy.get() + json_len, 0, SIMDJSON_PADDING);
simdjson::dom::parser parser;
simdjson::dom::element element = parser.parse(padded_json_copy.get(), json_len, false);
````

Setting the `realloc_if_needed` parameter `false` in this manner may lead to better performance since copies are avoided, but it requires that the user takes more responsibilities: the simdjson library cannot verify that the input buffer was padded with SIMDJSON_PADDING extra bytes.

Source: https://github.com/simdjson/simdjson/blob/master/doc/performance.md#padding-and-temporary-copies

**Comment by lemire** [comment]
@devshgraphicsprogramming If you think my answer clarifies your question, please close the issue, if not, please elaborate.
