### ISSUE TITLE
Document how to handle "out of order" keys

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#1229]
The On Demand API iterators through the nodes and the keys in document order, like an event-based API (SAX). This makes the code order sensitive... which is fine by itself (after all, SAX is order-sensitive). We need to document some recommendations on how to handle cases where the order in not as expected, without introducing too much complexity.

Unfortunately not addressed by PR https://github.com/simdjson/simdjson/pull/1226

**Comment by jkeiser** [comment]
The primary way, with the current interface, to handle order insensitivity is to loop:

```c++
double x = 0, y = 0, z = 0;
for (auto field : obj) {
  if (field.key() == "x") { x = field.value(); }
  else if (field.key() == "y") { y = field.value(); }
  else if (field.key() == "z") { z = field.value(); }
}
```

Kinda sucks, but that's what it is.

This all makes me think that we should perhaps adopt a stricter policy for lookup, where `obj["x"]` is still order-sensitive, but we don't skip values automatically. Then there's never a chance that you will unintentionally skip fields you actually want to handle later. It could well be worth doing this before 0.6, as it's a LOT safer, leaving you no chance of screwing up. You might reject some documents you would otherwise accept, but there's no chance of accepting a document but not getting the right values (which is the stated intent of On Demand--that is the WORST kind of surprise).
