### ISSUE TITLE
Move cmake min version to 3.12

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1262]
Currently we support cmake 3.9 and below. This is old and has significantly hampered our ability to write clean cmake code.

As I recall, 3.12 is the version with most of the improvements I've wanted, at least.

When we last visited this, Ubuntu stable had 3.9 and we couldn't switch. Ubuntu 20 is now at 3.17, Debian stable is now at 3.13, we should be OK to switch.

**Comment by friendlyanon** [comment]
The top level lists would eventually require CMake 3.13. This was pointed out in https://github.com/simdjson/simdjson/pull/1248/commits/361d9839bdb12a48ac3812bac079760b94d494c5 and [this](https://github.com/simdjson/simdjson/blob/master/cmake/simdjson-flags.cmake#L88) is the reason why, as that command did not exist prior to CMake 3.13.  
So for consuming this project, the above version is a requirement and has been since [this commit](https://github.com/simdjson/simdjson/commit/4015f46b7de8fe788e767cc50b77f034f8e215e3), but it went undocumented.

However, for running tests, benchmarks and other, [CMake 3.14](https://cmake.org/cmake/help/v3.14/release/3.14.html#modules) would be required because of the `FetchContent_MakeAvailable` calls.

**Comment by pauldreik** [comment]
>  So for consuming this project, the above version is a requirement and has been since [this commit](https://github.com/simdjson/simdjson/commit/4015f46b7de8fe788e767cc50b77f034f8e215e3), but it went undocumented.

Nice catch!

Maybe we should put a note under prerequisites https://github.com/simdjson/simdjson#quick-start which says something about the cmake version? (By the way, I love that the list starts at 0 :-)

**Comment by lemire** [comment]
@pauldreik Our documentation deliberately does not assume that people rely on CMake. There is actually little about CMake. In fact, many of our known downstream users do not rely (and cannot rely) on CMake. We do document how one can use simdjson as a CMake dependency, but that is about all there is. 

Now, of course, it would be nice to tell people that *if* they use CMake, then they should have at least version X. We need to be careful, however, not to create a dependency of the documentation on specific parameters that could change... not a great thing... so it would be most useful to document it if we can freeze the CMake version requirement.

You do not want to have too many moving parts.

Importantly, we do not want to have CMake as a end-user requirement. Many people do not use CMake, and cannot use CMake. There might be a political stance to take whereas we require everyone to rely on CMake, but I don't think it is particularly useful to do so here.

**Comment by lemire** [comment]
Closing.
