### ISSUE TITLE
Allow download-free builds

### ISSUE THREAD

**Issue by xkszltl** [simdjson/simdjson#1331]
**Is your feature request related to a problem? Please describe.**

Currently there're several downloads from github, for benchmarking, in cmake build.
Issues with this approach:
1. Some CI system bans network access in build.
2. It is a bad idea to have download during build due to stability reason.
3. For builds in some environment, especially in China, we want to use mirror instead of github itself.
  - Personally I often get several KB/s from github, not always but frequently. This makes it very unreliable when used in automated systems.
  - It is much easier to replace github URL with mirror's, while there's no easy way to find them all in cmakelists.

**Describe the solution you'd like**

Put them in submodules.
If there's future plan to use submodule for simdjson itself while keeping benchmarking libs download-as-needed, you can add a middle-layer repo, e.g. simdjson-benchmark, which carries all those benchmarking submodules and can be easily switched on/off in main repo.

**Comment by lemire** [comment]
If you are not a contributor to the simdjson library, you can simply build with `SIMDJSON_JUST_LIBRARY=ON` and you will not get any downloads whatsoever. It will be thin and fast.

If you are having to download all of the dependencies, then it is because you need the tests and benchmarks to be build. Can you elaborate on your use case? If you are not actively developing simdjson, and you are just a user, then I strongly recommend you try `SIMDJSON_JUST_LIBRARY=ON`. It will be much, much faster.


About the issue at hand...


Please note that we had submodules initially.  There was widespread agreement among the simdjson contributors at the time to remove submodules... See
https://github.com/simdjson/simdjson/pull/1258

Among other things, we were able to improve the performance of the build, somewhat significantly...
https://github.com/simdjson/simdjson/pull/1258#issuecomment-721359572

We are unlikely to reverse this engineering work. It may not be perfect, but it is quite efficient.

This being said, let us see if we can help... 

> For builds in some environment, especially in China, we want to use mirror instead of github itself.

That's a valid concern. Currently, we use the following function to retrieve compressed releases from GitHub... I believe that we would need to change a single line...

https://github.com/simdjson/simdjson/blob/a56149e79a573fa63b0b321cd19c1612c48ac168/dependencies/import.cmake#L17

(file import.cmake)

and maybe this other line as well....


https://github.com/simdjson/simdjson/blob/b632107a7ac544f424d2e865d45ff4ca5ffc02cb/dependencies/CMakeLists.txt#L52

So exactly two lines would need to be changed. We could easily change our CMake script so that one can pass a mirror URL to github. It seems easy enough, don't you agree? If that helps you, we can make this change.

Of course, you may also well redirect the github.com domain locally and temporarily to another IP if you have the proper accesses.

> Some CI system bans network access in build.
> It is a bad idea to have download during build due to stability reason.


We don't download during the builds, we download during the cmake configuration... And that part is meant to be cached.

You are definitively not supposed to be downloading the dependencies with every build. If this happens to you, please elaborate.


In general, the downloads must occur anyhow, unless the dependencies are cached. If the dependencies are not cached, then git will have to download the submodules, and CMake will have to download the compressed release files. In either case, you either need a cache or network access. Without network access, CI won't work.

If the downloads fail, then some of our unit cases will fail. However, it is true in either case.

In both cases, one can cache the dependencies. We do cache dependencies when using GitHub actions, for example...

```yaml
      - uses: actions/cache@v2
        with:
          path: dependencies/.cache
          key: ${{ hashFiles('dependencies/CMakeLists.txt') }}
```

**Comment by xkszltl** [comment]
@lemire 
Thanks for the detailed explanation!

We generally build dependency packages by themselves in advance, not as part of its downstream application builds.
This means it is hard to tell whether our build is correct (runnable without linkage error), and unit test is usually helpful here.
Regarding "benchmark", currently we don't have a strong need for that, but would like to make it "one switch away" for whoever wants that in the future.

> So exactly two lines would need to be changed

The first line is for downloading `.zip`, not `git clone`.
Not every git repo site allows source code downloading as zip.

The second line depends on GitHub release, which can be replaced as a file link into repo itself.
That's doable but we want to avoid hard-coding a commit hash on our side that will soon diverge from v3.9.1 tag.

Regarding these 2 lines, it would be better to call standard git API/URL rather than GitHub-specific ones.

> You are definitively not supposed to be downloading the dependencies with every build. If this happens to you, please elaborate.

Yes we reclone every time for cleanness (keep it and `git clean -dfx` won't help in this case since they're not tracked by git).
And for CI (mostly Azure Pipeline in our case), machine is wiped our everytime, but in some case we can cache the git repo itself.

And "config" is usually treated as part of "build", not part of "download" in CI context.

We also want to make sure everything we used for build are tracked by git and represented by git commit hash.
This is also a hard requirement sometimes for compliance reason.

**Suggestion**

If I understand correctly, the reason (and build acceleration) of removing submodule is coming from "clone only what you need".
In this case I would recommend an approach that works with both git/cmake:
1. Put everything as submodule.
2. Set something like "submodule: false" in CI config, or clone without `--recursive`.
3. In CMake, add `find_package(Git)` and init submodules you need during build.
  - Don't put a `REQUIRED`. You can check submodule dir before use, and ask user to download manually if empty. This allows user to build in a pre-cloned repo without hard-dependency to git at build time. Could be possible if someone loves svn (not me!), or want to build on embedded device.

This way you get a standard and static git repo that works with broader git ecosystem, while keeping downloading minimum.

**Comment by friendlyanon** [comment]
Additional downloads are only necessary for the benchmarks, which shouldn't be part of the root lists file by default, because then dependents - like you - are forced to deal with such things unnecessarily.  
Removing these from the root lists file is something I plan on doing in the near future, but I'm a little swamped IRL so I haven't had time to continue my activities regarding this library.

As @lemire pointed out, if you are using `simdjson` by making it part of your build tree, then you can just `set(SIMDJSON_JUST_LIBRARY ON CACHE INTERNAL "")` before the `add_subdirectory`/`FetchContent_MakeAvailable` command call and you only get the library itself without all the development stuff.

If that, for whatever reason, is not an option, you can still point the import logic at a directory using `simdjson_DEPENDENCY_CACHE_DIR` env variable, and if the dependency is found there, then the import will be a noop. See [import.cmake](https://github.com/simdjson/simdjson/blob/c805fc28a49c2970898f5379acd68f89fba8cb9a/dependencies/import.cmake#L10-L15).

**Comment by xkszltl** [comment]
@friendlyanon 

> if you are using simdjson by making it part of your build tree ...

As mentioned above (https://github.com/simdjson/simdjson/issues/1331#issuecomment-740126889), we're not making it as part of build tree.
Instead we build simdjson, install to a staging dir, packaging as deb/rpm/... and install in target system for use.

`SIMDJSON_JUST_LIBRARY` is not an option in this case because it disables unit test as well, which is critical for our QA after build.

> you can still point the import logic at a directory using simdjson_DEPENDENCY_CACHE_DIR env variable

Thanks for letting me know, not aware of this option before.
However, as mentioned above (https://github.com/simdjson/simdjson/issues/1331#issuecomment-740126889), in most of our use case, only whatever managed by git can survive across builds. So where to cache doesn't really matter to us.

Besides, downloading to src dir and building upon a dirty dir, seems to be the opposite direction of cmake's out-of-source build philosophy.

**Comment by lemire** [comment]
> SIMDJSON_JUST_LIBRARY is not an option in this case because it disables unit test as well, which is critical for our QA after build.

You can set both of these options to false which will only disable the related benchmarks:

```CMake
option(SIMDJSON_COMPETITION "Compile competitive benchmarks" ON)
option(SIMDJSON_GOOGLE_BENCHMARKS "compile the Google Benchmark benchmarks" ON)
```

We can add other options as well depending on your needs. You should be able to build the library and test it without downloading dependencies. Right now, the only remaining dependency (after setting the above options to OFF) is cxxopts, which is tiny. If even a tiny library is too much, we can work to get around even that.

I realize you would much prefer that we maintain our dependencies as git submodules. As a stated in my first answer, I don't think that it is likely to happen. We are not going to just undo @friendlyanon's work and go back to how things were originally.

You want to avoid downloads. That's reasonable and we can work to accommodate that.

**Comment by lemire** [comment]
I have renamed the issue. We are not reintroducing submodules. We can, however, improve our support for download avoidance if that is an issue.

**Comment by friendlyanon** [comment]
> Besides, downloading to src dir and building upon a dirty dir, seems to be the opposite direction of cmake's out-of-source build philosophy.

From git's point of view the source tree is never dirtied by the default location of the dependency cache, it's ignored in a .gitignore and it should survive between builds, as they rarely need invalidation (only when contents of `dependencies/CMakeLists.txt` hash differently do we invalidate in CI, as change most likely means a dep's commit hash was changed).

> `SIMDJSON_JUST_LIBRARY` is not an option in this case because it disables unit test as well, which is critical for our QA after build.

Interesting. Would installing a known good version that passes CI satisfy such a requirement? Is there something unsatisfactory about the CI system in place for this library?

> cxxopts

Technically, it's already optional, as the tools only build in the presence of its target.

**Comment by xkszltl** [comment]
> I have renamed the issue. We are not reintroducing submodules. We can, however, improve our support for download avoidance if that is an issue.

I understand people can have different taste about how download/submodule should be handled.
I mainly suggest a way that can work well with both submodule and on-demand download, in case you haven't thought about that possibility.
It is still up to the author.
I don't have any hard requirement for pushing that approach.

I think it is probably going off-topic.
Avoiding download is not the original concern, instead I'm asking if we can download from standard git API (submodule is only one of that. git clone from repo is also an option), rather than GitHub-specific file URL or repo zip, so that we can easily inject alternative URL to help with download.

**Comment by xkszltl** [comment]
> If even a tiny library is too much

2 cases:
1. In China, downloading from GitHub can varies from 1KB/s to > 1MB/s depending on load of international connection. <= 100KB/s is normal and the 1KB/s side is very problematic.
2. (This is not what we currently used for simdjson, so mostly bring up for awareness) We have some CI system that simply block network access (delete NIC driver) after initial downloading, to keep build "clean and tracked" for compliance requirement.

For me downloading cxxopts (<1MB) doesn't cause much trouble on speed side.
It mainly causes trouble in:
- Stability. Can have stalling https connection, or occasionally connection-reset-by-peer (TCP reset). May need timeout and retry logic around cmake for fully automated build.
- Impossible to do a fully offline build, without calling cmake first for pre-downloading.

**Comment by lemire** [comment]
@xkszltl I think that @friendlyanon has come up with something good that will be even better for you than submodules. It will be faster than what you have been doing I can assure you.

**Comment by pauldreik** [comment]
Glad you all solved this without resorting back to the unintended git submodule ping-pong again!

**Comment by lemire** [comment]
You will be able to set SIMDJSON_ALLOW_DOWNLOADS to OFF to solve this particular issue.
