### ISSUE TITLE
Difficulty with documentation

### ISSUE THREAD

**Issue by DaManJ** [simdjson/simdjson#1448]
Hi, just had a very bad experience with 'unresolved externals' when trying to compile code using the .get() method.

I think you should make explicit in the documentation that these errors will be encountered unless the type passed to get() is in an explicit list of types.

unresolved external occurs when passing:
std::string (needs to be passed std::string_view - does not work with std::string)
long (needs to be passed int64_t - does not work with long).

Due to unresolved externals being very obscure errors this would be much better to make more clear in the documentation.

Thanks

**Comment by lemire** [comment]
Good points.

**Comment by jkeiser** [comment]
At this point, we should just replace the templated get with a set of overloads. It's not buying us anything and this is the second time we've heard this woe since 0.8.

**Comment by rychale** [comment]
Hi,

I had the same issue, so I've put this as a default implementation for element::get:

```
template<typename T>
inline simdjson_result<T> get() const noexcept
{
      static_assert(!sizeof(T), "Not implemented");
}```

So now when I use get with not supported type I get compilation error.

Kind regards,
Alexey

**Comment by lemire** [comment]
@rychale Thanks.

We are going to retire this template from our public API. It is evidently a usability nightmare.

**Comment by lemire** [comment]
@rychale Your proposal can be useful... let me try it out.

**Comment by jkeiser** [comment]
oh wow, that would be so much better than deprecating! I'd love to see that with get<T>(T&) too :)

**Comment by lemire** [comment]
@jkeiser See my PR. We can "undeprecate" if you'd like as it only involves removing comments that I recently added.

My main motivations for deprecating `get<simdjson::dom::arrray>` are that...

1. I think that `get_array()` is just nicer.
2. We do not otherwise document `get<simdjson::dom::arrray>`.

I think that there is a concept whereas you do not want to encourage too much variation in the usage of your public API.

But I have no strong feeling.

**Comment by rychale** [comment]
Please let me add two cents.

I agree that for structural fields like objects and arrays `get_object()/get_array()` are much easier to use. But for edge fields, like strings and numbers the right`get<T>()` can be chosen based on template parameter type.

I know you have `operator T()`, but sometimes it wont work without `static_cast`.

Kind regards,
Alexey

**Comment by lemire** [comment]
@rychale 

> But for edge fields, like strings and numbers the rightget<T>() can be chosen based on template parameter type. 

Can you give me a code example? I find it hard to think about these issues without an example.

**Comment by rychale** [comment]
I was trying to come up with some good example of why does `template<typename T> get()` is nice to have available.

One reason is that user can specialise it for a custom type like:

```c++

template<>
Person element::get<Person>() const
{
   auto* elem {*this};

   return {
      .name = elem["name"],
      .age = elem["age"]
   };
}
```

**Comment by lemire** [comment]
Right. And the following would not be possible because C++ (unlike other languages) does not allow you to add methods to an already declared class....

```C++
Person element::get_person() const
{
   auto* elem {*this};

   return {
      .name = elem["name"],
      .age = elem["age"]
   };
}
```

That's a good argument for keeping it around.

**Comment by jkeiser** [comment]
Yep, that's how `nlohmann_json` uses it. I think people will use `.get<T>(T&)` this way as well. We don't really advertise this feature yet, but it exists (and was intentional, patterned from nlohmann_json :). I was willing to drop the support like a hot potato when it caused massive user headaches, but with this fix I think it might be just fine.

Also, the templated version allows you to write generic code *calling* into simdjson. This is illustrative, but I feel there are likely better examples when you combine the custom `T` getter with it.

```c++
struct JsonNumber {
  ondemand::value val;
  template<typename T>
  T operator+(const T &other) { return val.get<T>() + other; }
};
```

**Comment by lemire** [comment]
So I merge code that leaves the templated get.

It turns out that the we just needed to provide a failing default implementation. I like it when the solution is simple.
