### ISSUE TITLE
Consider stricter parsing

### ISSUE THREAD

**Issue by nico-abram** [simdjson/simdjson#1458]
This article ["An Exploration of JSON Interoperability Vulnerabilities"](https://labs.bishopfox.com/tech-blog/an-exploration-of-json-interoperability-vulnerabilities) about exploits and vulnerabilities because of (rfc compliant) json parser differences was released today.

I would like to bring it to the attention of the maintainers, to know if you would be willing to fail on some cases where the spec is ambiguous. The article presents a couple examples of possible vulnerabilities because of this ambiguity (And tech stacks that use different parsers) and explicitly suggests that parsers:

 - Generate fatal parse errors on duplicate keys.
 - Do not perform character truncation. Instead, replace invalid Unicode with placeholder characters (e.g., unpaired surrogates should be displayed as the Unicode replacement character U+FFFD). Truncating may break sanitization routines for multi-parser applications.
 - Avoid deviating from the chosen specification, or provide a "strict" mode that adheres to the RFC 8259 (or relevant) definition.
 - Produce errors when handling integers or floating-point numbers that cannot be represented faithfully.

I just wanted to breing this issue to the attention of the maintainers (I searched the issue tracker and could not find a similar prior discussion about duplicate keys, which according to [the docs](https://github.com/simdjson/simdjson/blob/master/doc/basics.md#standard-compliance) is intentional ("We do not enforce key uniqueness")) so some discussion can potentially happen. I think it would be perfectly acceptable to close this as wontfix (Because of backwards compatibility, performance, or some other reason), but at least wanted to bring it up.

**Comment by lemire** [comment]
This article has me puzzled. It claims that Ruby simdjson would parse

``` JSON
 {"description": "Comment support", "test": 1, "extra": "a"/*, "test": 2, "extra2": "b"*/}
```

as...

``` JSON
{"description":"Comment support","test":2,"extra":"a","extra2":"b"}
```

The simdjson library itself will refuse to parse the input as it is invalid. It will simply bail out entirely.

```
$ ./build/tools/json2json comment.json
 Parsing failed. Error is 'The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.'.

$ more comment.json
 {"description": "Comment support", "test": 1, "extra": "a"/*, "test": 2, "extra2": "b"*/}
```



> Produce errors when handling integers or floating-point numbers that cannot be represented faithfully.

That is our behaviour.


> Do not perform character truncation. Instead, replace invalid Unicode with placeholder characters (e.g., unpaired surrogates should be displayed as the Unicode replacement character U+FFFD). Truncating may break sanitization routines for multi-parser applications.

The article you refer to claims that Ruby simdjson has Character truncation of the type "Collision through stray quotes".


As for simdjson, we check for strict UTF-8 compliance as per the latest JSON specification. There is no possible character truncation. We do not replace invalid unicode characters with placeholder characters, nor will we. There is no concept of unpaired surrogates in UTF-8.

Note that the article you refer to describes JSON as a UTF-16 format, but as per the latest JSON specification, it is a UTF-8 format.

> Generate fatal parse errors on duplicate keys.

We provide all keys and it is up to the library user to decide how to handle duplicated keys. Importantly, we do provide *all* keys, including the duplicates, so the user gets a copy of what is serialized and can easily determine whether there was a duplicate.

If you receive `{"test": 1, "test": 2}`, you will get two keys (test and test). If, as a user of simdjson, you want want to consider this scenario as an error, you can.

```
$ ./build/tools/json2json dup.json
{"test":1,"test":2}
$ more dup.json
{"test": 1, "test": 2}
```

> I could not find a similar prior discussion about duplicate keys, which according to the docs is intentional ("We do not enforce key uniqueness")) so some discussion can potentially happen. I think it would be perfectly acceptable to close this as wontfix (Because of backwards compatibility, performance, or some other reason), but at least wanted to bring it up.

Yes. It is intentional. We leave it up to our users to decide what to do in such cases. It is important to understand that unlike the scenarios explored in the article you link to, we do not, for example, keep the first or the last key. We keep them all.


The article you refer to indicates that they are problems with Ruby simdjson. This might be so. But I cannot verify them in simdjson itself. If you can reproduce them, please open an issue with such a case. We will be eager to fix them.

Otherwise, I would encourage you to take the concerns to Ruby simdjson: 
https://github.com/saka1/simdjson_ruby
It would be most useful to them if you can provide reproducible issues.

**Comment by lemire** [comment]
I am closing after having reviewed the potential issues. The reporter should open a new issue if they can provide a reproducible issue.

**Comment by nico-abram** [comment]
Thank you for your response. I'll look into simdjson_ruby

My apologies for wasting your time
