### ISSUE TITLE
stack size and boost::fiber

### ISSUE THREAD

**Issue by bgemmill** [simdjson/simdjson#1517]
**Describe the bug**
boost::fiber has a default stack size of [128kb](https://github.com/boostorg/context/blob/boost-1.75.0/src/posix/stack_traits.cpp#L96), and much like #691, running simdjson inside a boost::fiber with `-fsanitize=address` is enough to blow out the stack. 

It's possible that this issue is all ready being addressed looking at #1515, feel free to close if so. 

Thank you for the `-Wframe-larger-than=100000` idea to track this down!

**To Reproduce**

Use simdjson inside boost::fiber with clang's address sanitizer, and run the demo code from [here](https://github.com/simdjson/simdjson/blob/master/doc/basics.md#using-the-parsed-json) like this:
```
void simdjson_tests() {
  using namespace simdjson;
  using namespace std;
  
  ondemand::parser parser;
  auto cars_json = R"( [
{ "make": "Toyota", "model": "Camry",  "year": 2018, "tire_pressure": [ 40.1, 39.9, 37.7, 40.4 ] },
{ "make": "Kia",    "model": "Soul",   "year": 2012, "tire_pressure": [ 30.1, 31.0, 28.6, 28.7 ] },
{ "make": "Toyota", "model": "Tercel", "year": 1999, "tire_pressure": [ 29.8, 30.0, 30.2, 30.5 ] }]
)"_padded;

  // Iterating through an array of objects
  for (ondemand::object car : parser.iterate(cars_json)) {
    // Accessing a field by name
    cout << "Make/Model: " << std::string_view(car["make"]) << "/" << std::string_view(car["model"]) << endl;

    // Casting a JSON element to an integer
    uint64_t year = car["year"];
    cout << "- This car is " << 2020 - year << "years old." << endl;

    // Iterating through an array of floats
    double total_tire_pressure = 0;
    for (double tire_pressure : car["tire_pressure"]) {
      total_tire_pressure += tire_pressure;
    }
    cout << "- Average tire pressure: " << (total_tire_pressure / 4) << endl;
  }
}


int main(int argc, char** argv) {
  boost::fibers::fiber f([](){
    simdjson_tests();
  });
  f.join();
  return 0;
}
```

With the warning enabled, on compilation we get:
`stack frame size of 132856 bytes in function 'simdjson_tests' [-Werror,-Wframe-larger-than=]`

**Configuration:**
 - OS: ubuntu 20.04.2
 - Compiler: clang version 11.1.0
 - Version: simdjson 0.9.1

**Comment by lemire** [comment]
@bgemmill Thanks for the report. Running sanitizers may increase the stack usage significantly. If you use sanitizers in a threaded environnement, I recommend making allowance for the stack size. With Boost fiber, you should probably use segmented stacks  (BOOST_USE_SEGMENTED_STACKS). Please try that and report back.

The issue you link to is distinct: we were allocating large blocks of memory (e.g., 4kB) on the stack in our tests. This is normally safe enough (at least as part of unit tests) but if you combine a memory-limited container with sanitizers, you get problems.

The simdjson library itself does not allocate large blocks of memory on the stack. All large blocks of memory are dynamically allocated (heap).

**Comment by bgemmill** [comment]
@lemire Thanks for getting back.

Regarding segmented stacks, I've used them before and the Rust folks summed up the experience [pretty well](https://mail.mozilla.org/pipermail/rust-dev/2013-November/006314.html).

Stepping back for a minute, it seems like simdjson uses a lot of stack in unoptimized code even with the address sanitizer off.

If we turn off the address sanitizer in this example, we see: `stack frame size of 76536 bytes in function 'simdjson_tests' [-Wframe-larger-than=]` 

If we turn on debug optimizations `-Og`, stack usage drops below 1000 bytes and everything works as expected.

While `-Og` works for me now that all the debugging has been done, it feels a like a gotcha... turn on address sanitizer and get segfaults! :)

Given that the optimized code seems fine, and appetite to fix up unoptimized code may be limited, is this worth mentioning in the documentation for people using address sanitizers?

**Comment by lemire** [comment]
Pull requests invited!

**Comment by lemire** [comment]
@bgemmill The link you offer argues that segmented stacks are slow. But if you run your code with sanitizers and without optimization, you are surely not expecting high performance?

**Comment by bgemmill** [comment]
@lemire Thanks for getting back again.

The two major use cases I have are:
1) Debug mode while developing, address sanitizer on most of the time. <== Here's where I saw the blowups.
2) Release mode for regression testing and deployment, all optimizations on. Address sanitizer on sometimes if there's a bug to hunt down.

So in the usual development cycle, using simdjson, turning on the sanitizer, and seeing blowups _only in debug mode_ was a surprise.

Release mode cares a lot about performance, and that's how I came to try out simdjson in the first place! 

Because of that, I'm hesitant to use split stacks there. For determinism when debugging, I'd prefer to use the same stack system in debug and release.

**Comment by lemire** [comment]
@bgemmill 

Let us circle back. This issue was opened as a potential bug. I removed the bug label because I think there is no bug as I understand it. A bug is an actionable issue: there is a problem, we can identify it, and fix it, and then verify that it was fixed.

If one is compiling the code without optimization, and without instructing the compiler to keep the stack usage in check, in  a thread environment with limited stacks, and with the addition of sanitizers that further increases the stack usage... then one may suffer from stack issues.

The most obvious fix is not to do that. If you want to use little stack space, and use sanitizers, then do not compile in debug mode or otherwise instruct you compiler to reduce stack space.

Importantly, we do not control how you build your code nor which tools you use. It is not clear what we can do. We are only a C++ library that does not rely on stack for storage: our data is on the heap. I understand that you do not want to grow your stack even in debug mode. I understand that you want to develop in debug mode without optimization, and with the memory sanitizers. I am not arguing with you.

All I am saying is that I do not see a bug on our end. Now, maybe I am wrong and there is a bug in our code. It is entirely possible. But if so, I would invite you to help us identify it and, better yet, help the project by providing a patch through a pull request that may improve matters. I am totally open to reverting my stance and to declare this to be a bug.

**Comment by lemire** [comment]
@bgemmill To be clearer, as far as I can tell, I agree with everything you wrote. So I am not debating with you. What I am telling you, however, is that it is not clear to me what we can do to help.

**Comment by bgemmill** [comment]
@lemire Thanks for getting back again.

The issue as I understand it is: `stack frame size of 76536 bytes in function 'simdjson_tests'`

_Is this a bug?_

My reaction on seeing that was [very similar to yours](https://github.com/simdjson/simdjson/issues/691#issuecomment-611842406) in the thread about macos.

The overflow on the mac side was deemed enough of a bug to [apply a fix in simdjson](https://github.com/simdjson/simdjson/pull/692) so that debug mode just works.

This appeared to be enough of a bug on one platform to get a fix, so it seems like a bug to me.

_So what to do?_

If surprising large stack usage has been found on two different platforms, either:
1) Why is it using so much stack? Solving this would remove the macos special case and prevent further reports.
2) Should the documentation mention compiling in debug mode with `-Og` more prominently so it doesn't come up?

I'd like to get your thoughts on which one is best since you as the author are in a far better place for estimating if option 1 is worth it than I am.

**Comment by lemire** [comment]
@bgemmill I understand that you believe that it is a bug in the library. I'll repeat what I stated earlier: pull requests are invited. The easiest way to demonstrate that it is a bug is to investigate the issue and provide a fix.

**Comment by lemire** [comment]
@bgemmill Regarding documentation, our document is tied to established experience and various tests. If you would like to contribute documentation on how to use simdjson with Boost Fiber and memory sanitizers, that would be great. We could add a SANITIZER.md or BOOSTFIBER.md documentation file. Please tie the documentation to additional tests so that the documentation can be verified and tested (in CI ideally).

**Comment by lemire** [comment]
I am going to close this.

If one runs the code without optimizations, with memory sanitizers and in a context where the stack space is limited (e.g., within some threads), you may hit limits. As the reporter has found, in debug mode under macOS, we disable threaded execution for that reason.

That's the recommended fix here too: (1) configure your system to have more stack space, or (2) turn on optimization.

Code or documentation contributions are invited.
