### ISSUE TITLE
Extracting size of the array before iterating

### ISSUE THREAD

**Issue by KordianD** [simdjson/simdjson#1574]
For me this parser is much faster than other ones! Thanks.

One question:

How to extract number of elements from array before iterating? Is is possible?

    #include "simdjson.h"
    #include <vector> 
    #include <iostream>

    using namespace simdjson;

    int main(void) {
        
        ondemand::parser parser;
        auto json = "  { \"number\": [ 40, 39, 37, 40 ] }"_padded;

        ondemand::document test  = parser.iterate(json);

        std::vector<int64_t> parsedNumbers;    //! How many elements in json to initialize?
        // std::vector<int64_t> parsedNumbers ( number_of_elements_in_number_array_from_json)

        for (const int64_t number: test.find_field("number"))
        {
            parsedNumbers.push_back(number);
            std::cout << number << std::endl;
        }
    }

I would like to initialize std::vector<..>  and omit reallocation in the for loop.

This `number` array has 4 elements but other json can have 10000.

Is it possible?

**Comment by lemire** [comment]
You cannot currently. When you enter the array, the array has not yet been parsed.

I have PR https://github.com/simdjson/simdjson/pull/1539 which allows you to scan the array, count the number of elements and then rewind it with knowledge of the element count.

This PR is not merged because @jkeiser has another approach which might be preferable where you would get at the array, you'd fork, and have two iterators, one could be used to count the number of elements and the other one to parse the elements.

**Comment by KordianD** [comment]
Thanks for answering!
I am waiting for  this functionality, especially when I have a lot structures with std::vector<..> and such reallocation is common thing. Hopefully, it will be faster.

**Comment by lemire** [comment]
@KordianD We are going to need this functionality for the R wrapper in any case, for much the same reason. So it is definitively coming.

We prefer to move more carefully so we can think it through and not have to change the API due to design mistakes later.
