### ISSUE TITLE
Low performance despite haswell AVX2 support 

### ISSUE THREAD

**Issue by sguinebert** [simdjson/simdjson#1727]
- OS: [e.g. Ubuntu 20.04 LTS]
 - Compiler gcc 9
 - Version 9
 - Optimization setting  Make: make -j64 -O3

**results of code below 

boost elaspsed :  7  ms
simdjson v1.0.0
Detected the best implementation for your machine: haswell(Intel/AMD AVX2)
simdjson elaspsed :  69  ms
simdjson elaspsed :  69  ms**

```
#include <QElapsedTimer>
#include <boost/json.hpp>
using namespace boost::json;
#include <simdjson.h>
using namespace simdjson;

static std::string readfile(const std::string path) {
    std::ifstream file(path, std::ios::binary);
    return std::string(std::istreambuf_iterator<char>(file >> std::skipws), std::istreambuf_iterator<char>());
}
int main(int argc, char *argv[])
{
    QElapsedTimer timer;
    auto jsonraw = readfile("gsoc-2018.json");

    timer.start();
    value jv = parse(jsonraw);
    qDebug()<< "boost elaspsed : " << timer.elapsed() << " ms";


    std::cout << "simdjson v" << STRINGIFY(SIMDJSON_VERSION) << std::endl;
    std::cout << "Detected the best implementation for your machine: " << simdjson::active_implementation->name();
    std::cout << "(" << simdjson::active_implementation->description() << ")" << std::endl;

    ondemand::parser parser;

    timer.restart();
    ondemand::document tweets = parser.iterate(jsonraw);
    qDebug()<< "simdjson elaspsed : " << timer.elapsed() << " ms";

    padded_string json = padded_string::load("gsoc-2018.json");
    timer.restart();
    ondemand::document tweets2 = parser.iterate(json);
    qDebug()<< "simdjson elaspsed : " << timer.elapsed() << " ms";
return 0;
}
```

**Comment by lemire** [comment]
We have some extensive benchmarks, see https://github.com/simdjson/simdjson/tree/master/benchmark

We are always eager to receive new contributed benchmarks, and you can (should) write your own benchmarks.

A benchmark should start with the definition of a given task. Here, it is unclear to me what you are benchmarking. The line ` parser.iterate(json)` is not a reasonable target because all it does is scan and index the file.

If you'd like to report a bug in simdjson, please follow our bug template at https://github.com/simdjson/simdjson/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
