### ISSUE TITLE
can we define a build option to skip check_next_input()?

### ISSUE THREAD

**Issue by wanweiqiangintel** [simdjson/simdjson#1954]
In stage1, simdjson checks the input in the function check_next_input(). If the input is ASCII, the function will return true directly. Otherwise, it will call check_utf8_bytes(). But if we can ensure the input is valid in the upper application, can we define a build option to skip the function check_next_input()? Thanks!

**Comment by lemire** [comment]
@wanweiqiangintel You are proposing to skip the UTF-8 validation. I investigated this possibility but we can validate inputs at 30 GB/s or more on many systems...  This means that skipping this validation would not make a large difference (at least not for the accelerated kernels).

**Comment by wanweiqiangintel** [comment]
I have compared the performance of json parse benchmark w/ or w/o check_next_input() in my icelake machine. The result is as below:
w/ UTF-8 validation:
![image](https://user-images.githubusercontent.com/89506884/220817397-47cf74f9-323f-4ccb-a0d5-84966beb3008.png)

w/o UTF-8 validation:
![image](https://user-images.githubusercontent.com/89506884/220817434-c58be153-bd54-4709-9400-a0e3c7238f0d.png)

From the performance result, we can see about 17.1% performance improvement in stage1 and 7.5% performance improvement in all stages. Maybe this is significant from a very fast baseline.

**Comment by lemire** [comment]
According to your numbers, you are saving roughly 0.1 instructions per byte (3.1633 instructions per byte to 3.0507 instructions per byte). I submit to you that I was truthful when I wrote "skipping this validation would not make a large difference".

Pull request invited. Note that
- UTF-8 validation should be done by default, since this is a requirement of the specification.
- It should not slow down existing routines (the feature should have 'zero cost').
- We need tests.

A little bit of extra bloat (binary size of the library) is acceptable.

Possibly this could be made available as a compile-time macro. It does not seem like a lot of users will seek this feature, so it might be acceptable to limit to those who are willing to compile the library with a flag.
