### ISSUE TITLE
Significant size increase for single header files

### ISSUE THREAD

**Issue by marmeladema** [simdjson/simdjson#2047]
Hi!

Not an issue per say, more like a question: is this expected that the size of the single header files almost tripled with latest release 3.2.2?

## Release 3.2.1

simdjson.cpp 674 KB
simdjson.h 1.24 MB

## Release 3.2.2

simdjson.cpp 1.74 MB
simdjson.h 3.53 MB

I tried to look at the diff but basically both files have been entirely rewritten.

Thank you for taking a look :bow:

**Comment by lemire** [comment]
The relevant change in the release notesfor version 3.2.2 is  `Get headers compiling in editor` by @jkeiser which leads to https://github.com/simdjson/simdjson/pull/2031 The notes on this PR explain what is being done, with some details regarding the effects:

  - All generic and implementation-specific files include their dependencies in a `#ifndef SIMDJSON_AMALGAMATED`.
  - Generic files hide their include guards behind `#ifndef SIMDJSON_AMALGAMATED` (this just makes it so files can include each other in-editor without worrying about dups).
  - If you are editing a generic file, it will compile it against the most advanced available implementation, so that things like simd will be loaded in and be testable. (This is particularly useful when editing src/ files; most of stage1 doesn't compile under the fallback implementation.)
  - clangd is now the recommended VS Code extension.
  - `simdjson.cpp` is now fully independent of `simdjson.h` (don't have to include both anymore)
  - `#include "simdjson.h"` will not process any implementations except the builtin one (where before it would process all of them, even though it only needed the builtin one for ondemand). This doesn't make simdjson.h appreciably smaller, but it should be faster to compile.
 - `simdjson.cpp` no longer includes the full simdjson.h, only getting what it uses. 

Let us test it out...

On my ARM based laptop (LLVM 14), here is the compiled output...

Release 3.2.1
```
> c++ -O3 -c simdjson.cpp -std=c++17 && ls -alh simdjson.o
-rw-r--r--  1 dlemire  staff    86K  3 aoû 11:13 simdjson.o
```

Release 3.2.2
```
> c++ -O3 -c simdjson.cpp -std=c++17 && ls -alh simdjson.o
-rw-r--r--  1 dlemire  staff    85K  3 aoû 11:11 simdjson.o
```


So the library got slightly smaller.


On a Linux server with GCC 11 and targeting x64 processors...

Release 3.2.1
```
$  c++ -O3 -c simdjson.cpp -std=c++17 && ls -alh simdjson.o
-rw-r--r--. 1 dlemire dlemire 259K Aug  3 11:16 simdjson.o
```

Release 3.2.2
```
$  c++ -O3 -c simdjson.cpp -std=c++17 && ls -alh simdjson.o
-rw-r--r--. 1 dlemire dlemire 259K Aug  3 11:17 simdjson.o
```

So the binary size has not changed. Note that the x64 binaries are larger because it needs to support multiple different processors (we rely on runtime dispatching).

We may look at compilation time, let us consider the x64 system:


Release 3.2.1
```
$ time c++ -O3 -c simdjson.cpp -std=c++17

real	0m6.726s
user	0m6.493s
sys	0m0.207s
```

Release 3.2.2
```
$ time c++ -O3 -c simdjson.cpp -std=c++17

real	0m6.001s
user	0m5.818s
sys	0m0.163s
```


So the compilation is slightly faster in this case.

@marmeladema  Could you elaborate on your concern? Are you literally concerned with the size of the amalgamated source files? Maybe your concern is that 2 MB is a lot of data? I am personally not looking at the size of the source files though I do pay attention at compilation times and size of binary outputs.

Please consider: [In 2018, the average popular web page was larger than 2 MB](https://www.pingdom.com/blog/webpages-are-getting-larger-every-year-and-heres-why-it-matters/).

**Comment by jkeiser** [comment]
It is a little bigger than I expected; but I did add a bunch of comments to the amalgated file so one can see what was skipped or changed.

**Comment by striezel** [comment]
@lemire: Thanks for providing the numbers about compilation time and binary sizes.
But I guess the even more relevant question is: How does the new version 3.2.2 perform in JSON parsing benchmarks compared to version 3.2.1 before the rewrite? Did somebody do the measurements for that?

**Comment by lemire** [comment]
@striezel In my tests, there was no difference in performance. The algorithms did not change and it is the same functions, they have just be reordered and they get amalgamated differently (with more redundancy). Note that we do have automated performance checks in CI...

https://github.com/simdjson/simdjson/blob/master/.github/workflows/ubuntu20-checkperf.yml

Of course, if you are concerned, I do invite you to run your own benchmarks.

**Comment by lemire** [comment]
I am going to close this issue for now. Concerned people are invited to run tests and/or provide pull requests.

**Comment by jkeiser** [comment]
One of the reasons it increased (though I wouldn't have thought it was a big reason) is that the new code emits comments for every line it skips. I would be surprised if that added up to 2MB, though!
