### ISSUE TITLE
Possible to support `ppc` via Altivec? (i.e. for non-VSX ISA)

### ISSUE THREAD

**Issue by barracuda156** [simdjson/simdjson#2158]
Currently only `ppc64` (`ppc64le` or bi-endian?) is implemented: https://github.com/simdjson/simdjson/tree/c4654553dd11711966a30c6810ce324ef59a5cb6/include/simdjson/ppc64

Is it possible to support `ppc` via Altivec? Would be awesome.

**Comment by lemire** [comment]
POWER processor have a 64-bit ISA since 2001 (POWER4). I expect that all POWER processors in operation run in 64-bit mode. The simdjson only provides accelerated kernels for 64-bit processors. We will not provide accelerated support for 32-bit hardware.

If you mean that you want big-endian POWER support, then I would invite a pull request. It is my understanding, however, that POWER systems available for purchase today are little endian  by default, and that has been true for many years. Big endian systems are legacy at this point.

**Comment by barracuda156** [comment]
@lemire Thank you for responding.

All POWER cpus, AFAIK, are bi-endian, including the latest, and there are a number of currently supported OSs which run in Big-endian mode on POWER and PowerPC systems.

**Comment by lemire** [comment]
Currently, simdjson should work on a big endian POWER system, although without acceleration. If you need accelerated support on big-endian POWER processors, then I invite a pull request.

Note that we need to be able to run tests. Currently, we have support for ppc64le in our testing framework. If you need accelerated support for ppc64be, please make sure to include the necessary tooling so that we can support it.

So I am going to close this. Your pull request is invited.
