### ISSUE TITLE
parse broken json

### ISSUE THREAD

**Issue by ahao1995** [simdjson/simdjson#2183]
I may receive a broken json，like`{"op":"t`, I try to parse use this code
```
std::string sub_code = R"({"op":"t)";
padded_string padd_str = padded_string(sub_code);
ondemand::document doc;
ondemand::parser parser_;
auto ret = parser_.iterate(padd_str).get(doc);
std::string_view op;
ret = doc["op"].get(op);
```
and then got a coredump, how to deal with this case, is there some method to check it is broken and not to parse

**Comment by jkeiser** [comment]
I'm guessing this is in a function, and you return the string_view from the function?  And the core dump happens when you access that string_view after the function returns? 

For efficiency reasons, the string_view points at memory allocated inside the parser object. When that goes out of scope (or when you reuse it to parser another document), all string_views become invalid. You should either store and return a std::string, or keep the parser object alive until you are done using the object. For many use cases we actually recommend the latter for many use cases: keeping the parser object around and reusing it to parse other documents can drastically reduce memory allocation (and thus increase performance). If you do this, though, just make sure you finish using any string_views you get before you parse another document with the same parser object!

**Comment by jkeiser** [comment]
Actually, in this case simdjson should be returning an error. Are you checking whether ret contains an error before using "op"? If not that would explain the core dump because the string view will not be set to anything.

**Comment by ahao1995** [comment]
> Actually, in this case simdjson should be returning an error. Are you checking whether ret contains an error before using "op"? If not that would explain the core dump because the string view will not be set to anything.

thanks, I know, I do not check ret, it contains an error actually.
