### ISSUE TITLE
Significantly increased compilation time when using tag_invoke.

### ISSUE THREAD

**Issue by RealTimeChris** [simdjson/simdjson#2300]
Compiled and run on Windows 10.0.20348 using the MSVC 19.42.34433.0 compiler, release mode with the /O2 flag.

Alright so I have a performance-benchmarking repo for a few json libraries, and when going from this:
https://github.com/RealTimeChris/Json-Performance/blob/reversion/Source/Simdjson.hpp
to this:
https://github.com/RealTimeChris/Json-Performance/blob/benchmarking-new/Source/Simdjson.hpp
Compilation time goes from roughly 8min20s:
https://github.com/RealTimeChris/Json-Performance/actions/runs/12244845455/job/34157445426
Up to roughly 1h8m8s:
https://github.com/RealTimeChris/Json-Performance/actions/runs/12244604828/job/34156694760

Any idea how to fix this?

**Comment by lemire** [comment]
I have not examined the source code you provided, but if you are hitting very long compile time, the first step is to look for a compiler issue. Generally, with simdjson under Windows, I recommend using ClangCL (LLVM). Visual Studio in release mode generates inferior binaries and has slow compile time.


I have a blog post on this topic: [Regular Visual Studio versus ClangCL](https://lemire.me/blog/2023/02/27/visual-studio-versus-clangcl/). The regular visual studio compiler can have atrocious compile time (when targeting release). 

I am going to close this. If you *also* find an issue with ClangCL (LLVM), then please open a new issue. Otherwise, I would invite you to direct your concerns at the Microsoft Visual Studio support team.

If you still believe that there is an issue in simdjson, please provide an analysis. Feel free to open another bug report, but please provide specifics.
