### ISSUE TITLE
Getting elements inside mutiple layers of arrays causes exception raised wrongly

### ISSUE THREAD

**Issue by thoh-testarossa** [simdjson/simdjson#2311]
I have a json string like this:
```
str = {"data" : {"T" : 0, "b" : [["1"], ["2"], ["3"], ["4"], ["5"]], "a" : []}}
```

and I try to use such the code to parse this struct (like things in quickstart_ondemand.cpp):
```
simdjson::omdemand::parser p;
simdjson::ondemand::document d = p.iterate(simdjson::padded_string(str));
auto b = d["data"]["b"].get_array();
auto b_size = (size_t)b.count_elements();
for(size_t i = 0; i < b_size; i++)
{
    auto b_l = b.at(i).get_array();
    auto b_l_size = (size_t)b_l.count_elements();
    for(size_t j = 0; j < b_l_size; j++)
        printf("%s", b_l.at(j).get_string().value().data());
}
```
This will lead to an exception raised when parsing the second array element ["2"]. It this a bug or just a misuse case?

**Comment by lemire** [comment]
You are using the `at` method to iterate through an array, something we specifically and explicitly disallow... precisely because we want to discourage the code you wrote (as it is inefficient).


See the documentation of the function: 
<img width="1031" alt="Screenshot 2024-12-10 at 11 35 26 AM" src="https://github.com/user-attachments/assets/00e11c9b-c389-48e7-b4c8-ba0362702323">

See `basics.md` where  this is explicit:

<img width="1037" alt="Screenshot 2024-12-10 at 11 34 41 AM" src="https://github.com/user-attachments/assets/e327e13c-ed92-44dc-9ca3-1325375a549a">

For the inner array, because the array only contains one element, `at` is allowable. The following code should work...

```C++
using namespace simdjson;
void example() {
  ondemand::parser parser;
  const padded_string json =
      R"({"data" : {"T" : 0, "b" : [["1"], ["2"], ["3"], ["4"], ["5"]], "a" : []}})"_padded;
  ondemand::document d = parser.iterate(json);
  auto array = d["data"]["b"].get_array();
  for (auto value : array) {
    std::cout << value.at(0).get_string() << std::endl;
  }
}
```
