### ISSUE TITLE
Support for API to Create Null-Terminated String Buffers for C Interoperability

### ISSUE THREAD

**Issue by Cirnoo** [simdjson/simdjson#2318]
Hi,

I encountered an issue when working with simdjson and its ondemand API. Here is a simplified code snippet to demonstrate the problem:

```cpp
#include "simdjson.h"
#include <string>
#include <cstdio>

int main() {
    std::string json = R"({
        "name": "Alice",
        "age": 30,
        "city": "Wonderland"
    })";

    simdjson::ondemand::parser parser;
    simdjson::ondemand::document doc;
    doc = parser.iterate(json);

    for (auto field : doc.get_object()) {
        auto key = field.unescaped_key().value();
        simdjson::ondemand::value value = field.value().take_value();
        printf("key = %s\n", key.data()); // Example for C API, without string length
    }
    return 0;
}
```
I expected the output to be:

```
key = name  
key = age  
key = city  
```
However, the actual output was:

```
key = name": "Alice",  
        "age": 3  
key = age": 30,  
        "city": "Wonde  
key = city": "Wonderland"  
    }
```
Upon investigation, I realized this happens because simdjson reuses the storage from the original JSON string instead of creating new strings. While this design is efficient, it creates issues when working with C APIs (like printf in this example) that expect null-terminated strings.

**Feature Request**:
Would it be possible to provide an API in simdjson that creates a null-terminated string buffer for `simdjson::simdjson_result<std::string_view>` ? This would simplify interoperability with C APIs, as it avoids manual handling of string lengths.

Currently, I work around this by manually copying the string into a std::string before passing it to the C API, but this adds overhead and complexity.

Thank you for your excellent work on simdjson!

Best regards~

**Comment by lemire** [comment]
JSON strings may contain a null characters.

Consider the following:

```C++
#include "simdjson.h"
#include <string>
#include <cstdio>

int main() {
    auto json = R"({
        "na\u0000me": "Alice",
        "age": 30,
        "city": "Wonderland"
    })"_padded;

    simdjson::ondemand::parser parser;
    simdjson::ondemand::document doc = parser.iterate(json);

    for (auto field : doc.get_object()) {
        std::string_view v = field.unescaped_key();
        std::cout << v.size() << std::endl;
    }
    return EXIT_SUCCESS;
}
```

If you run this program, you will notice that the first key has 5 characters (`v.size()`). The first key has a null character in third position. So a spec-compliant JSON parser cannot rely on null-terminated C strings. Of course, C functions do take a length parameters (`strncpy`, `strncmp`).

If your concern is with printing, you can print a `std::string_view` using `printf` as follows:

```C++
#include <stdio.h>
#include <string_view>
int main() {
  std::string_view key = "fds";
  printf("key = %.*s\n", int(key.size()), key.data());
}
```

This will work even if the key contains null characters because you specify the length.

In C++23, you can do...

```C++
#include <string_view>
#include <print>
int main() {
  std::string_view key = "fds";
  std::print("key = {}\n", key);
}
```

If what you want is to create a C string, you can do it as follows:

```C++
char* string_view_to_cstr(std::string_view str) {
  // Allocate memory on the heap for the C-style string
  char* cstr = new char[str.size() + 1]; 

  // Copy the string data to the heap-allocated memory
  std::memcpy(cstr, str.data(), str.size());

  // Add the null terminator
  cstr[str.size()] = '\0';

  return cstr;
}
```
... although, of course, you should check that the source does not contain null characters. And don't forget to free the C string!

That's clearly not very satisfying to have to check for null characters. A better solution, if you need to interop with C, is to use your own string data structure:

```C++
typedef struct {
  const char* data;
  size_t length;
} simdjson_string;
```

and then you can do the conversion like so...


```C++
simdjson_string sv_to_simdjson_string(const std::string_view& sv) {
    simdjson_string result;
    result.data = sv.data();
    result.length = sv.length();
    return result;
}
```


In any case, I am closing this issue. If you have options that you would like us to consider, please consider providing a pull request.
