### ISSUE TITLE
write tutorial on how to use simdjson

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#382]
Currently all we have in terms of documentation are the comments in the code and the README:

https://github.com/lemire/simdjson#navigating-the-parsed-document

We need an actual tutorial. 

cc @davidglavas

**Comment by lemire** [comment]
Related issue: https://github.com/lemire/simdjson/issues/293

Help needed.

**Comment by davidglavas** [comment]
In order for people to start using simdjson asap it would be useful to have a short document with for example the following structure:

- how to set up simdjson (the "Usage: easy single-header version" section in the readme is good)
- present a simple json document on which operations that simdjson offers will be executed
- use `get_corpus`
- use `build_parsed_json` (or alternatives)
- use `is_valid`
- show how to navigate the parsed json document (eg. extract values at different levels)
- ... (apply other operations simdjson supports to the example json document)

**Comment by lemire** [comment]
I agree.

**Comment by ywiyogo** [comment]
For an example, if I have this JSON Array, how can I navigate and iterate the array?
```
[{
      "Date": "28.12.2012",
      "User": "Mr.X",
      "Height": 170,
      "Age": 50,
      "Hobby": "Reading"
    },
    {
      "Date": "02.10.2013",
      "User": "Mr.Y",
      "Height": 180,
      "Age": 40,
      "Hobby": "Tennis"
    }
]
```
Is it possible to access the elements such as `cout<< pj.get(0).getValue("User")`<<endl`?

**Comment by jkeiser** [comment]
Actually, I just checked in a new iteration interface you can use for that.

### Preamble

Assume this preamble:

```c++
#include "simdjson.h"
using namespace simdjson;
int main(void) {
  document::parser parser;
  parser.allocate_capacity(1024);
  document people = parser.parse(get_corpus("people.json"));
  // insert usage code here
}
```

### Iteration and Indexing

To print all users:

```c++
for (document::object person : people.as_array()) {
  cout << string(person["User"]) << endl;
}
```

To get just the first one:

```c++
document::object person = *people.as_array().begin();
cout << string(person["User"]) << endl;
```

### Iterating Objects

If you want to print out every key/value pair of each person, you can iterate that too:

```c++
for (document::object person in people.as_array() {
  cout << string(person["User"]) << ":" << endl;
  // Read all key/value pairs in the person. key is std::string_view, value is document::element
  for (auto [key, value] : person) {
    cout << "  " << key << ": ";
    if (value.is_string()) { cout << string(value); }
    else if (value.is_uint64_t()) { cout << uint64_t(value); }
    cout << endl;
  }
}
```

## Other Thoughts

This does make me think we should have a direct `<<` for elements and results, since it's super common and the string(...) is annoying to read. But until then, a tutorial should do what is possible, not what is desired :)

NOTE: We haven't added a direct array indexer because people would get the wrong idea about its performance (it's not constant time and we shouldn't pretend it is :)). However, it's a standard iterator, so `advance()` will work to get (for example) people[1]:

```c++
document people = document::parse(get_corpus("people.json"));
auto person = people.as_array().begin();
std::advance(person, 1);
cout << (*person)["User"] << endl;
```

**Comment by ywiyogo** [comment]
Thanks @jkeiser, since I would like to integrate the single header one, I found out that `document::object` is not declared neither in the header `simdjson.h` nor `simdjson.cpp`. I can find it only in _include/simdjson/document.h_ and its cpp file.
Is it intentionally that the `document::object` doesn't included?

**Comment by jkeiser** [comment]
Hmm, that probably needs to be updated in master. Run `make amalgamate` and use the files from `singleheader`.

**Comment by jkeiser** [comment]
I feel this is done, at least well enough for 0.3, [here](https://github.com/simdjson/simdjson/blob/master/README.md#code-usage-and-examples). Let's file further issues for improvements or changes we want to make.
