### ISSUE TITLE
64 or CACHE LINE SIZE ?

### ISSUE THREAD

**Issue by DBJDBJ** [simdjson/simdjson#460]
```cpp
// padded_string -- line#  34
  char *padded_buffer = aligned_malloc_char(64, totalpaddedlength);
```
I am not 100% certain, but that 64 is cache line size? If it is, it should be 128 for ARM CPU's.

In any case 
```cpp
#if defined(__x86_64__) || defined(_M_AMD64)
#define SIMDJSON_CACHE_LINE_SIZE 64
#endif
#if defined(__aarch64__) || defined(_M_ARM64)
#define SIMDJSON_CACHE_LINE_SIZE 128
#endif
```
And then perhaps
```cpp
// padded_string -- line#  34
  char *padded_buffer = aligned_malloc_char( SIMDJSON_CACHE_LINE_SIZE , totalpaddedlength);
```

**Comment by DBJDBJ** [comment]
I understand. Perhaps then :

```cpp
// Irrespective of the cache line size
constexpr auto SIMDJSON_BLOCK_SIZE { 64 } ;
// portable version of  simdjson_memalign
namespace {
inline void * simdjson_aligned_malloc(size_t size_, size_t alignment_ = SIMDJSON_BLOCK_SIZE ) 
    {
           return simdjson::alligned_malloc(  alignment_ , size_  )  ;
    }
}
```

Just a suggestion.

**Comment by lemire** [comment]
@DBJDBJ It is a good observation.

This SIMDJSON_BLOCK_SIZE has a name, it is STEP_SIZE and it is found in stage1_find_marks.h. The actual value varies per architecture. Currently, it can be 64 or 128, depending on the architecture. There is probably no benefit to 128-byte alignment on hardware that has 64-byte cache lines, but there might be in the future.

Possibly, we could go with the highest block size that we have, which is currently 128.

Maybe there is a cleaner way to go about it.

cc @jkeiser

**Comment by jkeiser** [comment]
I think the step size is really talking about loop unrolling: the right number of 64 byte blocks to put into one loop iteration.

We should have a separate, larger step for cache size, imo: the number of bytes we want to fully process at once. The idea being that we process each n bytes of the file in multiple stages, each of which is a tight loop that does a small job really well, and pass information to each other through fixed or max length buffers.

As a possible example, a string parsing and detection loop, followed by atom and number parsing, followed by collection and brace matching loop, could decouple several branches with highly different cardinality.

The benefit being that each little stage has more registers available to use for constants and other preprocessing, and branches in a stage can hopefully be more predictable since they aren't compounded with everybody else's branches.

The con being that we'll often have to pass things around through memory that we were passing in registers, and that we'll end up with a separate for loop / branch for each stage, which presumably increases bpu load.

**Comment by jkeiser** [comment]
And I just commented something completely unrelated because I read cache size when you wrote cache line size. Never mind :)

**Comment by DBJDBJ** [comment]
In any case, I think it is about time to start collecting important constants scattered around into one place.

It seems this magical '64' is sometimes supposed to be '128'. Architecture depending. 

```cpp
// padded_string -- line#  34
  char *padded_buffer = aligned_malloc_char(64, totalpaddedlength);
```

**Comment by jkeiser** [comment]
I don't think the stage 1 constant is necessarily related to this; stage 1 is capable of processing documents of any length. But I agree, we should give these numbers names related to their purpose.

**Comment by DBJDBJ** [comment]
> This SIMDJSON_BLOCK_SIZE has a name, it is STEP_SIZE and it is found in stage1_find_marks.h.

@lemire @jkeiser 

I can see `STEP_SIZE` in ` stage1_find_marks.h` **only** as a template argument name.

Should I put  `#define SIMDJSON_STEP_SIZE 64 ` in `common_defs.h` ? And then use it in:

```cpp
// padded_string -
  char *padded_buffer = aligned_malloc_char( SIMDJSON_STEP_SIZE , totalpaddedlength);
```

**Comment by jkeiser** [comment]
It's a per-architecture constant: I'd make a namespaced constant under `simdjson::haswell`, `simdjson::westmere`, etc. It seems like a good idea to gather those into one place.

**Comment by DBJDBJ** [comment]
Until now it was just a number 64.  Do we just do as I suggested and do a proper CPUID() call in the future release?

**Comment by jkeiser** [comment]
The stage 1 step size matches the cache line size, sounds like, but I have no idea if it always will / should. The differences in the 64 and 128 byte templates are more complex than just reading more memory. It's also a compile time value by necessity (but you could compile different versions for different cache lines).

All that is a complicated way to say "I don't know," though :) I can't figure out a criteria to have a clear opinion one way or another.

**Comment by DBJDBJ** [comment]
OK then I will make a macro ... the future "ideal situation" :) can be resolved behind it later on ...
