### ISSUE TITLE
comparison: `GDC fast` 2X faster according to https://github.com/kostya/benchmarks#json

### ISSUE THREAD

**Issue by timotheecour** [simdjson/simdjson#482]
according to this benchmark https://github.com/kostya/benchmarks#json GDC fast (implemented in D and using a custom library https://github.com/mleise/fast/blob/master/source/fast/json.d) appears to be 2X faster than `C++ simdjson`

obviously that benchmark is rather limited (it parses a single large json file) but still, I'm curious whether GDC fast could be included in your evaluation?
/cc @mleise

**Comment by mleise** [comment]
I haven't touched that code in ages. It was particularly optimized for that benchmark on a Haswell mobile CPU, which happened to work well with what the author of the benchmark was using for comparisons. It maps the whole file to memory, so that rules out extremely large or streamed JSON and probably has some overhead for many small files, but was perfect for that benchmark.
And while I was shooting for twice as fast as RapidJSON, the fastest parser at that time, it was still surprising to see the numbers. And now the code just sits there in #1 spot, rotting, but never dethroned.
You'll probably want to know that I don't do a complete validation for the benchmark, but a limited one on the data that is requested. So if there is a Unicode problem in some string that the host program wants to skip over, it goes unnoticed. - I know, I know, but NVIDIA does it.

**Comment by lemire** [comment]
On that particular benchmark, simdjson is entirely bound by page allocation. The recommendation you will find in our README is to use huge pages when working with large JSON files. More on this point later.

The issue of comparing against libraries written in other programming languages was raised repeatedly and closed (by me). We are not going to be comparing against libraries in Java, Rust, D, Swift... within the core simdjson project. This is a C++ project. We compare against C and C++ libraries. But, in fact, you could reasonably question whether comparisons done against other libraries really belong within the core simdjson library? And, of course, we try hard to compare against fully validating libraries (like RapidJSON). It might be fine to do partial validation, but that is not what we currently do.

Of course, @mleise's library is super clever and that D is a great programming language, but we are not going bring his D library into simdjson as a dependency to simdjson. And I do want to praise @mleise : there is a lot to like regarding the API and cleverness of that library. I am not being dismissive... (I invite everyone to study its great API!!!)

But, yeah, no D, no Rust, no Java here. (Which does not mean we are against cross-language comparisons, just *not in the core simdjson library* project.)

However, I am not going to close this issue, because this benchmark does illustrates a good point that other contributors to simdjson should be aware of... it is basically how we handle large files. We have not yet resolved this concern to a satisfying degree. 

The benchmark in question just goes in an sums up a lot of floats. Float parsing is, by itself, a bit nasty and ill-defined. But simdjson just can't manage to even keep the CPU feed (doing float parsing) on that benchmark if you have small (4kB) pages. And that has to do with the fact that simdjson will just allocate and use a whole lot of out-of-cache memory in this test.

On many systems, you can't allocate 4kB pages at speeds much higher than 3GB/s. Given that we are (currently) strictly single-threaded on regular JSON files... and that the kernel waits for us to touch a page before allocating it... This puts a hard limit on how fast we can go. E.g., if you were to do the parsing at 3 GB/s (which is fast), you would end up with a 1.5GB/s total parsing speed when considering page allocation *to store the document itself*. Now factor in the fact that simdjson needs to allocate a lot more memory than that... and you see how we are quickly in big trouble on this benchmark. You are just not going to parse at gigabytes per second... ever... with no parser that needs to do a lot of memory allocation. The easiest fix is to go with huge pages, as it makes the whole thing go away. But if you want to stick with small pages, then you have no choice to go faster: allocate less memory.

If you want to study this benchmark, try to process increasingly large files starting from a small file. Since it is just a long list of triples, you can adjust the length as you see fit. You will see the interesting effect when the performance of simdjson just starts choking despite the fact that it is the same json. You will see the number of user-space instructions per cycle fall and then the number of cycles per second fall... while the kernel does its page allocations... 

So it is a good benchmark to illustrate a weakness of the current simdjson.  In fact, I think we should turn it into a synthetic benchmark that we can use for future work, at some point.

Note that we are working on this and simdjson should be able to handle that particular benchmark much better in the future.

cc @jkeiser

**Comment by lemire** [comment]
For people who are too lazy, here is the benchmark in question...

```D
    struct Coord { double x, y, z; }

    string text = readText("/tmp/1.json");
    text ~= "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";
    double x = 0, y = 0, z = 0;
    auto json = Json!(trustedSource, false)(text, No.simdPrep);
    auto coords = json.coordinates.read!(Coord[]);

    foreach (ref coord; coords)
    {
        x += coord.x;
        y += coord.y;
        z += coord.z;
    }
```

**Comment by lemire** [comment]
And the next thing you have to worry about, after small page allocation, in this specific benchmark is number parsing. Number parsing is a nasty, nasty problem.

To sum things up, that benchmark is a memory + float parsing benchmark. Currently, simdjson gets in trouble with the memory stress.

**Comment by lemire** [comment]
I am closing this.

**Comment by jkeiser** [comment]
Based on that benchmark, we might want to add this "DAW JSON Link" to our benchmarks here. Like to be as fair as we can!

**Comment by lemire** [comment]
Sure.
