### ISSUE TITLE
Get fuzz_minify working

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#530]
Presently, we [do not build fuzz_minify](https://github.com/lemire/simdjson/blame/master/fuzz/CMakeLists.txt#L30) in CI:

```
set(SOURCES
  fuzz_parser.cpp
#  fuzz_minify.cpp   # <--- does not pass the build check test on oss-fuzz, says "partially instrumented". help needed!
```

We need to figure out why it says "partially instrumented" and, well, un-partial it :)

**Comment by pauldreik** [comment]
It is because it had a huge table of precomputed numbers which leads to a large amount of code. That lowers the ratio of "active" code as measured by the oss fuzz tools such that it thinks that something is wrong with the build (as if only a subset of code was compiled with the proper fuzz flags). Perhaps it is possible to enable this now after your recent merge? To do so, one needs to carry out the "local testing" steps outlined on oss-fuzz, specifically the "check build" step: https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally

This sounds like it has my name on it, unless you want to give it a try!

**Comment by lemire** [comment]
@pauldreik Please go ahead if you can help with this issue...
