### ISSUE TITLE
oss-fuzz: what are we doing about the bugs?

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#573]
I have been basically ignoring the oss-fuzz "bugs". One bug refers to code we no longer have...

https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=-opened&can=1&q=proj:simdjson

There are build failures, but I am not sure what they are.

Someone needs to document how we are to work with oss-fuzz...

**Comment by lemire** [comment]
@pauldreik  Can you help?

**Comment by lemire** [comment]
E.g., should we be going there and manually closing the bugs?

**Comment by pauldreik** [comment]
Those bugs close themselves when they are fixed, very handy:-) The recent build failure is due to the libc++ problem. oss-fuzz uses a very recent clang and libc++ so problems related to those are likely to surface there first.

I see that https://github.com/simdjson/simdjson/blob/master/fuzz/Fuzzing.md does not give very much advice, before I improve it is there any more questions you think should be answered on that page?

**Comment by pauldreik** [comment]
The link you gave lists all issues, here is a link which lists only those which are open:

https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=-opened&q=proj%3Asimdjson&can=2

I think this works as it should, there is only one open at the moment which is the libc++ related build failure.

**Comment by jkeiser** [comment]
That one is verified too, after @lemire's fix. Looks to me like everything is closed now.

**Comment by lemire** [comment]
Thank you Paul.

**Comment by pauldreik** [comment]
My pleasure, it's great to be part of this project!
