### ISSUE TITLE
refresh fuzzing after recent changes

### ISSUE THREAD

**Issue by pauldreik** [simdjson/simdjson#585]
- [x]  The repository address has changed now when simdjson is an organization (yay!)
- [x]  fuzz_minify may work now after recent changes (see #530  )
- [x]  the documentation is lacking (#573 )
- [x]  github actions is not enabled on the new home
- [x]  add a fuzzing badge on the front page

**Comment by lemire** [comment]
Unrelated...  @pauldreik if you go to https://github.com/orgs/simdjson/people after logging off from GitHub, you will notice that you are not longer a visible member of simdjson. That's because organization membership is private by default. It you want people to know you belong to simdjson, you have to flip the switch.

**Comment by lemire** [comment]
I contributed a PR after seeing that you had opened this issue. I don't want to interfere with your work, so please just consider my PR as a possible part of the fix.

**Comment by lemire** [comment]
+1

**Comment by pauldreik** [comment]
All items are done, so closing.
