### ISSUE TITLE
Do we want to allow the copy construction of  document::object and  document::array as a matter of course

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#627]
Currently both document::object and  document::array get copy constructed on a routine basis. They are small (16 bytes) so you don't want to carry around pointers (explicitly so or implicitly so). However, my instinct would have been to use moves instead.

My understanding is that with the current code, the following line...

```
auto array = element.as_array();
```

Does copy construction.

**Comment by lemire** [comment]
cc @jkeiser

**Comment by jkeiser** [comment]
I was assuming the current code basically copied the reference (8 bytes) and the index (4-8 bytes depending on padding). Is that what you're talking about?

Now that I understand && better, I'm actually OK with having the conversion methods do moves, anyway. The signature could be of the form:

```c++
array_result element.as_array() && noexcept { }
```

Which would make it usable only if this was the last time `element` was ever used. (I think that's the 100% use case anyway).

I was assuming the optimizer would follow dataflow and do a move anyway, but there's no reason to bother given the wonder that is &&.

**Comment by jkeiser** [comment]
@lemire actually, one issue with that would be if people were using this pattern:

```c++
auto [array, error] = element.as_array();
if (!error) { do something with array }
auto [object, error] = element.as_array();
if (!error) { do something with object }
```

**Comment by jkeiser** [comment]
@lemire one hope I had was that the compiler would destructure element, object and array, and realize they all used the same document &, and share that in a single register. It would then only copy around the index. I haven't verified this and don't know if it's true. But detecting those extra instructions was a part of why I profiled the DOM APIs so carefully. It's an indication that it *could* be true, since the DocumentIterator *definitely* doesn't copy things around.

**Comment by lemire** [comment]
It is probably fine as it is. I just wanted to raise the issue so that it gets examined.

I am going to close it.
