### ISSUE TITLE
Given an array, the operator[] is for json pointer queries only...

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#631]
It is strange how, given an array, I can't access it with the operator[]. If I try, I will trigger a json pointer query.

cc @jkeiser

**Comment by lemire** [comment]
Note: I am not saying we need to change this API, but I think it needs to be documented, at least.

**Comment by jkeiser** [comment]
Not having an operator [int] was on purpose, because I think people would be surprised to find that doing array[0], array[1], array[2] ... was an n^2 operation, and it furthermore seems like a likely thing to try.

I implemented [] for objects, on the other hand, because the usage pattern for that is usually to pick off a few keys, and the number of keys in an object is usually not huge, so performance expectations aren't going to be *way* off.

**Comment by lemire** [comment]
Ok. Then to resolve this, we just need better documentation?

**Comment by jkeiser** [comment]
I think so. I think the right resolution is to describe `at()` for arrays, along with a note of why we don't use `[]`, change `[]` for objects to be simple field lookup, and remove `[]` entirely from array.

**Comment by jkeiser** [comment]
Fixed by #644.
