### ISSUE TITLE
Consider removal of JsonStream.md

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#639]
We have documentation for the old API. I think we need to consider removing it. However, it seems that there is reasonable content there that could be reused.

https://github.com/simdjson/simdjson/blob/master/doc/JsonStream.md

@jkeiser  Do we want to issue a release with old documentation?

**Comment by jkeiser** [comment]
Yeah, I left it there because I figured there was probably good in-depth information that could be salvaged for the architecture/design section at the very least. I don't think it's a dealbreaker to release with this in the repository given that there aren't links to it from the README and basics.md.

**Comment by lemire** [comment]
Ok. I suggest we remove it before 0.4 though. Marked in the 0.4 milestone.

**Comment by jkeiser** [comment]
I linked to it from RELEASES.md because it had better performance info ... I'll see if I can edit it quickly to make it use the right method/class names.

**Comment by jkeiser** [comment]
Fixed in #645
