### ISSUE TITLE
Switch to semantic versioning for releases.

### ISSUE THREAD

**Issue by TkTech** [simdjson/simdjson#663]
Switch to [semantic versioning](https://semver.org/) for releases. Resolves issues like #661 and makes things more consistent for external package managers as discussed in #656.

**Comment by lemire** [comment]
@TkTech  Can you elaborate... in which way are we not using semantic versioning?

Version 0.3.0 is still supporting the API from 0.2.1. We only deprecated some of it, but by my reading of the spec you offer, this is the correct thing to do.

**Comment by lemire** [comment]
To be precise... we followed this guideline...
```
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
```

We added functionality. Yes, there was deprecation... but that's as a warning, to tell people that they should move to the new API.

**Comment by jkeiser** [comment]
We did preserve backcompat as far as I know, but a relevant point of semantic versioning is that pre-1.0, [minor releases can be compat-breaking](https://semver.org/#spec-item-4). In fact, I think we want to remove deprecated functionality before 1.0 is released ...

So we could ask instead: do we want to release 1.0 sooner than later, so that we're on the semantic versioning "schedule," and people can take clearer dependencies?

**Comment by lemire** [comment]
Ok so I am going to close this since I think we are clearly using semantic versioning. We will bump the so version more frequently (that's already part of our scripted release schedule).

We can discuss release strategies. As things stand, I think we still want to go for 0.4. I guess once 0.4 is settled, we could discuss whether we want to go to 1.0.
