### ISSUE TITLE
Rationale for get<T> when exceptions are enabled

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#711]
When exceptions are enabled, there is no difference between casting elements of the DOM or calling get<type>... So why have get<type> at all?

**Comment by jkeiser** [comment]
Primarily because there are advantages to the no-exception API being a strict subset of the exception API: if they have some mutually exclusive APIs, then there is no API that you can be sure will work *no matter what the flags*.

This next point is minor, but I can also imagine users feeling having the cast on the right is a better representation of order of operations: `uint64_t(elem["a"]["b"])` makes uint64_t seem like the primary thing, where `elem["a"]["b"].get<uint64_t>()` puts the navigation first and then the cast. I found that style looked better in several cases, myself.

**Comment by jkeiser** [comment]
Actually, the better reason: the exception API is enabled by default. If you use simdjson without specifying any options, IMO, you should still be allowed to code in a no-exceptions style and it should still work. Just #include <simdjson.h> and start coding the way you'd rather code. Add -DSIMDJSON_EXCEPTIONS=0 later if you want to *enforce* a lack of exceptions.

**Comment by lemire** [comment]
@jkeiser 

I think we should offer this explanation to the users explicitly. :-)

**Comment by lemire** [comment]
This is what I try to do here:

https://github.com/simdjson/simdjson/pull/712

**Comment by lemire** [comment]
We have better documentation.
