### ISSUE TITLE
Publish and graph benchmark CI results over time

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#717]
It would be nice if we could see jitters and performance trends over time without doing a `git bisect` locally. If we could get CI to publish performance results somewhere, we could generate graphs automatically there.

Doing brief searches, I just can't find anything out there for this :( I'm assuming I just don't have the right word for it.

**Comment by TkTech** [comment]
Unless you're controlling the runners, I suggest against this. In sounds nice, but I actually *removed* this feature from pysimdjson's CI, which was using https://github.com/rhysd/github-action-benchmark.

On most of these (free) CI tools, you don't get consistent hardware, or you're possibly sharing the CPU with multiple other virtual hosts (which can brutally impact AVX performance). For example simdjson had to move off of travis.ci because a portion of the hosts didn't have AVX2. I found the results to be so wildly inconsistent it was pointless.

**Comment by jkeiser** [comment]
@TkTech yeah, one of the things I was thinking was having some of @lemire's boxes run a job at night on latest master, or something. He collects neglected hardware, after all :)

**Comment by lemire** [comment]
Yes. I almost gave this answer.

**Comment by lemire** [comment]
@yoannlr : Is this something you could help us with?

**Comment by lemire** [comment]
But yeah, we could easily have a cronjob running on some machine. It could somehow check for new commits, maybe daily, and then run some benchmarks, and maybe, somehow, upload a plot somewhere. Every little bit on its own is easy enough. But I don't have any experience with this sort of thing.

What would be cool would be a plot where you can zoom in and so forth... And also where different benchmarks can be recorded, so you can see how things evolve over time.

cc @yoannlr

**Comment by pauldreik** [comment]
I think this is a great idea! Even if running on the same machine, updates make the results not directly comparable. For instance, the mitigations for hardware bugs have had some negative impact on performance. 

I have made a similar system for a client. It stored results in an sqlite database, so it is easy to have all the meta data around and let several different machines participate. The presentation was made with python (pyplot) and a html page was updated, available on an internal web server.
All this was easy because the machines were on the same internal network and already had access to the same file system. The difficulty for simdjson is that someone needs to host this, and somehow publish the results in a secure way. Plus writing all that glue code...

**Comment by yoannlr** [comment]
Yes, that's something I could work on. I think it could be done with a cronjob, as you said, updating some sort of web page showing plots of different benchmarks.

**Comment by lemire** [comment]
Great. Let us see if we can make it happen!

**Comment by jkeiser** [comment]
> @jkeiser Could this be done using CMake, do you think?

@lemire I think it's probably something better done in Python or something. The actual performance run and/or upload could be done in either Python or cmake, but given my experience with cmake so far, I'd advise Python :)

As a sketch, I sort of think of it as a loop:

- When invoked, it gets:
  - the latest SHA from master
  - the last master SHA it ran against (probably stored in a file)
  - cpu and host signature
- Then it does a breadth-first binary walk of commits between latest master and the last run, *starting* with latest master (not starting with the middle). The purpose of this is to "fill in the gaps." I am quite sure there is a better way; this algorithm particularly won't go past the one from the previous run, even if there are commits that could be filled in there. For each checkin:
  - Checks it out
  - Builds it
  - Runs parse jsonexamples/*.json
  - Uploads the cpu and host signature along with the results to some central place. (This could easily be just a bulk copy operation so if the target host is down, you just dump this data to disk, continue on and upload when the host is up.)

**Comment by TkTech** [comment]
Keep in mind you can just use git bisect for this, it's one of the intended uses. `git bisect run benchmark.sh ...`

See https://git-scm.com/docs/git-bisect#_bisect_run

**Comment by lemire** [comment]
I love https://github.com/rhysd/github-action-benchmark#alert-comment-on-commit-page

(I am not a big fan of the idea of bisect for this. I think that bisect is designed to help you locate a problem when you know that there is a problem. It is not an intelligence tool providing an overview of how things are going.)

**Comment by jkeiser** [comment]
> I love https://github.com/rhysd/github-action-benchmark#alert-comment-on-commit-page

Oh nice! I don't know how you find these things. My Google fu isn't *that* bad, but when I went looking a couple of months ago, I found bubkis.

**Comment by yoannlr** [comment]
Hey! It's been a while, but after a few weeks of prototyping, I think I finally have a basis for this tool.

It's still a work in progress, but you can check it out on https://github.com/yoannlr/simdjson_benchmark_docker.

Unfortunately, my internship on simdjson ends here, but I see some possible evolutions for this tool (see the README) and might continue working on this tool, if time permits.

**Comment by lemire** [comment]
Ok. It is not perfect but I put I patched up version of @yoannlr approach online...

https://simdjson.org/plots.html


This should run automatically from now on.

It only runs on master.
