### ISSUE TITLE
Tweak the tape to make it cheaper to determine the element type

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#725]
Currently, we use the most significant 8 bits to indicate the type of element that the tape value refers to. It might be more performant to use the least significant 8 bits.

**Comment by jkeiser** [comment]
I was about to state my worry that the cast to int/double/etc. would get harder, but I guess that's not true: you already have to do an `&`, but with this, you could just do a `>>` (so same # of instructions, just different types).

Side note, is it "a `&`" or "an `&`"? If it was written out it would definitely be "an and." But since it's not, do we use the default "a"? It would make it sound awkward when spoken though, so I'm guessing you use the rule corresponding to the spoken word.

**Comment by lemire** [comment]
@jkeiser 

Part of the idea here is not so much to save on the instruction count, but on the price of instructions. A mask or a cast to a smaller type is almost always faster than a shift. In fact, a mask is often "free". So doing `a>>56` is more expensive than `a & 0xFF` on most hardware. And if you are casting the result to an 8-bit word... well...

I might write a blog post about this.

>I was about to state my worry that the cast to int/double/etc. would get harder

Why? So an int is "'l' << 56" followed by the value. We would now write "'l'" followed by the value.


> Side note, is it "a `&`" or "an `&`"?

I'm leaving this one to people who actually know the English language.

**Comment by lemire** [comment]
Though it is true that a shift is more expensive, my expectation now is that compilers largely handle it without the shift on x64. They load directly the byte that they need. On ARM, it is a different story, but it is unclear to me whether it is due to poor optimization on the part of the compiler or something more fundamental.

It is still possible that we end up with shifts in the binary output, but I am not longer hopeful that we have a quick way to a performance boost.
