### ISSUE TITLE
Port to POWER9

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#74]
There is demand to port this library to POWER9 

https://github.com/TkTech/pysimdjson/issues/9

I own a POWER9 box that I can make remotely available to someone interested in helping with the port.

cc @olgabot @TkTech

**Comment by TkTech** [comment]
Definitely happy to support it on the python side of things if a port is available. Need to look around for anyone hosting a buildbot on ppc for the simdjson and pysimdjson builds & tests.

**Comment by danlark1** [comment]
Hey, I am gonna outsource it to one of the students at the faculty of computer science in HSE university https://www.hse.ru/en/ under my guidance as a university project, I have enough experience with dealing SIMD in PPC, for example, the transition layer for x86_64 -> PPC [intrinsics](https://github.com/catboost/catboost/blob/master/library/cpp/sse/powerpc.h) so I believe I can manage this.

**Comment by lemire** [comment]
@danlark1 Please get in touch. I think that @jkeiser and myself will be happy to help.

I have a POWER8 server, if it helps.

**Comment by lemire** [comment]
(I meant POWER9 in my comment above.)

**Comment by danlark1** [comment]
@user959 is going to take this issue and start working shortly

**Comment by lemire** [comment]
Great.

**Comment by danlark1** [comment]
@TkTech we merged the ppc64 support, in order to build specifically for power8 and power9 at the same time you can use `"-DSIMDJSON_IMPLEMENTATION=ppc64;fallback"`, if you want to support only power9 I suggest adding flags `-DCMAKE_CXX_FLAGS="-maltivec -mcpu=power9 -mtune=power9" -DCMAKE_C_FLAGS="-maltivec -mcpu=power9 -mtune=power9"`, the implementation is the same, the compiler optimizations are a bit different. The performance difference is around 10%

**Comment by lemire** [comment]
Will be in 0.7.

@danlark1 Your name was added as a contributor.
