### ISSUE TITLE
public members

### ISSUE THREAD

**Issue by ostri** [simdjson/simdjson#782]
Is there some rule/policy when public members are used and when private members with getter and setter methods are user?
E.g. parser - nearly half of members are public and the others are private with getters/setters.

**Comment by jkeiser** [comment]
I don't think we specifically talked about it. However, I don't think we want to expose members publicly to users of the API.

So in `include/`, IMO, we want all members to be private, so people don't take a dependency on our internal datatypes. Since simdjson had existing users before we started really deciding what was public and what wasn't, we had to make some of them public for now, but marked them in doxygen as @private. Any member in include/ now should either be private, @private or @deprecated. If they aren't, let us know :) The exception is structures intended to work with C++14 destructuring (the `auto [x, y] = ...` syntax)--right now that's simdjson_result and key_value_pair.

In `src/` we're a lot more liberal about it. I don't really think we have a policy there, and I'm not sure we need one :) But I'd like to hear your opinion!

**Comment by ostri** [comment]
currently there are 77 members with public access. ;-)
in academia the answer is simple.
In real world, we need to be more conservative. I would start with some obscure clases. ;-)

**Comment by jkeiser** [comment]
Start with one though :) If it's public it probably has the documentation tag @private or @deprecated on it (or is in the internal namespace). Both of those mean we intend to either remove them or make them private in the future.

**Comment by lemire** [comment]
The public API *is* documented:
https://simdjson.org/api/0.3.1/annotated.html

**Comment by ostri** [comment]
> The public API _is_ documented:
> https://simdjson.org/api/0.3.1/annotated.html

Hm. By definition public API is everything in the header file. That's why we should keep it short. ;-)

**Comment by lemire** [comment]
> Hm. By definition public API is everything in the header file. That's why we should keep it short. ;-)

That is the definition in this project.

I am closing this issue.
