### ISSUE TITLE
Improve the performance of our API

### ISSUE THREAD

**Issue by lemire** [simdjson/simdjson#932]
We now have a revamped API which has got some praises. That is brilliant.

However, we are now trailing some other libraries by quite a margin... which shows that we could do better...

```
$ ./benchmark/parseandstatcompetition ../jsonexamples/canada.json
API traversal tests
simdjson                                        :   3.457 GB/s 1535.553 documents/s 
rapid                                           :   5.013 GB/s 2227.072 documents/s 
```

This is illustrated by PR
https://github.com/simdjson/simdjson/pull/931

**Comment by lemire** [comment]
Note that this is less important than it seems in the sense that parsing is always 10x slower than traversing. You are unlikely to be bound by the API traversal in practice.

Still... it seems that we have some fat to get rid off...

**Comment by TkTech** [comment]
For a practical example, iterating objects consumes 25% of pysimdjsons time on the github_events example. That time is entirely spent on this line: https://github.com/TkTech/pysimdjson/pull/33/files#diff-e8e9973ea260e0291f6baad184721677R47. 25% is the average between vtunes hardware sampling and py-spys software sampling.

This may be entirely reasonable, considering the number of objects in that example, but it compares against only 8% in orjson's visit deserializer. It's one of the reasons orjson does so much better than us in the benchmarks.

**Comment by jkeiser** [comment]
@TkTech I'm a little surprised that that line would be the issue (I totally believe it, I'm just surprised). There shouldn't be anything slow or even branchy about it. Meaning we *ought* to be able to bring it back down without contortions ... I hope.

**Comment by jkeiser** [comment]
In the future, I'm hoping we can throw the intermediate representation away entirely with [this method](https://github.com/simdjson/simdjson/pull/947) (which is not finished enough for you to use anyway), allowing us to go straight to the Python representation (or as straight as its API will allow).

**Comment by jkeiser** [comment]
That method also strives to share child iterators with parents, which we might be able to apply here as well--one of the less savory things we do here is, we completely consume the field value, meaning we've found our way to the "," after it; but then forget where we were and look at the start of the object to figure it out again (this should only be a couple of operations).

It's tricky to implement that sharing, though.

**Comment by lemire** [comment]
@jkeiser There is a lot going in in this code... Look at this for example...

```
inline PyObject* string_view_to_str(const std::string_view &s) {
     return PyUnicode_DecodeUTF8(s.data(), s.size(), "ignore\0");
 }
```


@TkTech  You may want to pass string_view instances per value instead of by reference.

**Comment by jkeiser** [comment]
It is unfortunate that Python doesn't seem to have a way to work with UTF-8 strings :/ But I only read through the API for all of about 10 minutes.

**Comment by jkeiser** [comment]
@lemire for bindings like this one, UTF-8 validation (even if it's fast) is not worth the time, since it will be validated when it is ingested to the host language.

SIMD UTF-8 *decoding,* on the other hand (with validation inside), would probably make a big difference.

**Comment by TkTech** [comment]
@jkeiser CPython predates the existence of Unicode by a few months. There's lots of legacy cruft in the interpreter that comes from many different ways of handling strings of very different platforms.

The UTF-8 validation is very fast relative to everything else, and we do actually want to keep it. The plan with pysimdjson is to push more filtering and processing out of Python and down into the extension (ala https://stedolan.github.io/jq/). For this, we still want the strings to be validated outside of CPython.

We can offer a faster interface that isn't compatible with the typical `json.loads` that uses [bytes & buffers ](https://docs.python.org/3/library/stdtypes.html#binary-sequence-types-bytes-bytearray-memoryview) instead of `PyUnicode_DecodeUTF8`.

**Comment by lemire** [comment]
How would UTF-8 decoding help the Python bindings? Python won’t eat any string without validation. 

Before we sacrifice anything upstream, I’d like to have the timings. So we parse at, say, 2GB/s. We could maybe reach 2.05GB/s if we gave up on UTF-8 validation. We could disable other things to help like object size computation. But my current guess based on previous benchmarks I ran is that the simdjson parsing accounts for less than 5% of the parsing time of the Python bindings. So there is nothing we can do. Sacrificing correct parsing is not worth it. 

The logic goes like this: if you are going to take all the elements and construct Python equivalent (dict, strings). This work in Python land will dominate the parsing time. 

It is not even Python specific. Even in C++, if you map everything to std::map, std::string... your performance will be terrible.

The solution, whether you are in C++, Python, JavaScript is to not do that. 

Note that it is true of all parsers. No parser that creates thousands of dict, strings, numbers... can be fast at the parsing stage. Even simdjson avoids that, with good reasons.

That’s what @TkTech means by pushing down the computation.

The other component of this approach is that you do not bring everything to Python. It is the numpy way. Numpy does not convert everything to Python types all the time. It has its own types. So instead of creating a dict in Python... you map the document from simdjson so that it acts like a Python instance without creating thousands of little objects.

Then you could parse in Python at the speed of simdjson because all Python would get is access to our objects. 


Of course the trick is to make it so that the user sacrifices nothing in convenience. And it is doable because few people using Python and JSON actually needs the whole DOM in pure Python. If anything, it must create crazy memory pressure.

**Comment by jkeiser** [comment]
> How would UTF-8 decoding help the Python bindings? Python won’t eat any string without validation.

My hope was that the buffer-to-string APIs would have a way to do that. Decode to buffer, translate to string with a promise that it's prevalidated, and voila! I know Rust has this kind of API, and hopefully others care about performance enough to have it, too :)

> Note that it is true of all parsers. No parser that creates thousands of dict, strings, numbers... can be fast at the parsing stage. Even simdjson avoids that, with good reasons.

Yes, we should try to skip expensive stuff (which includes string and number parsing) unless people ask for it, and when we do it, we should go straight to the language type instead of an intermediate.

**Comment by lemire** [comment]
> My hope was that the buffer-to-string APIs would have a way to do that. Decode to buffer, translate to string with a promise that it's prevalidated, and voila! I know Rust has this kind of API

But convert to what? According to random guy on StackOverflow... "In Python 3.3 and above, the internal representation of the string will depend on the string, and can be any of latin-1, UCS-2 or UCS-4, as described in [PEP 393.](https://www.python.org/dev/peps/pep-0393/)"

> hopefully others care about performance enough to have it, too :)

My impression is that the performance focused people use PyPy. And Pypy uses utf-8 internally... so there might be possibilities there.

**Comment by lemire** [comment]
>  I know Rust has this kind of API

My favorite language (which is not Rust) has that too...

<img width="660" alt="Screen Shot 2020-06-29 at 5 23 25 PM" src="https://user-images.githubusercontent.com/391987/86057591-735d2400-ba2d-11ea-98de-9470f8778e83.png">

**Comment by jkeiser** [comment]
Preface: sorry if I gave the impression I thought UTF-8 validation or decoding was the source of the problem here. I just noticed it and commented :) If @TkTech's profiling was accurate, it shouldn't have anything to do with it. (It's possible it's inaccurate though, due to our penchant for inlining--in which case the stuff on the next line could be the real issue.)

> But convert to what? According to random guy on StackOverflow... "In Python 3.3 and above, the internal representation of the string will depend on the string, and can be any of latin-1, UCS-2 or UCS-4, as described in PEP 393."

Depends on the data in the string and where it can fit :) It should be possible to detect what's needed, and *may* even be worth . I'm assuming Python doesn't have the ability to string several strings together. I'm not claiming it's a completely finished problem, but I'm also betting based on the UTF-8 validation problem that SIMD decoding hasn't been cracked yet either.

> My impression is that the performance focused people use PyPy. And Pypy uses utf-8 internally... so there might be possibilities there.

Yeah, it's going to change target to target. As a strategy we're best off making simdjson pluggable enough that we can target the language binding for each language specifically. And once we've made a few more planned improvements to the core, I think bindings are the next frontier (figure out if simdjson can be the best alternative for *everything on the planet*).

Target specificity is why I think redundant UTF-8 validation (it surely happens during decoding) is a place to reach for performance. It may only be 2%, but it's a *really easy* 2%--making it configurable will not be hard :)

> My favorite language (which is not Rust) has that too...

If it ran on machines I cared about, I suspect Swift would be my favorite language too. The spec had me salivating. They walked the language design tightrope really nicely.

**Comment by lemire** [comment]
Part of the issue has to do with exactly how you use the API. I am getting better results by treating dom::element as value types.

In some respect, constructing the DOM and then accessing it, will always be slower than what @jkeiser is working on... "on demand parsing". So there is a limit to how much we want to optimize the DOM tree for fast access.
