### ISSUE TITLE
Need estimates of CPU and memory overhead; does simdjson slow down core frequency?

### ISSUE THREAD

**Issue by JoeUX** [simdjson/simdjson#934]
**Describe the solution you'd like**
I'd like to see estimates of CPU and memory overhead. This is missing from the reported benchmarks.

---Please provide a clear rationale for the feature. Be advised that simdjson is a community-based project: you should consider providing help.

Estimated parsing speed isn't super useful without knowing the cost in CPU and memory, especially since I'd use it on-the-fly on a server handling various other chores.

I _expect_ simdjson to have fairly light overhead, but this is not mentioned or reported anywhere as far as I can see. I think it's pretty important for a lot of people to know the overhead, at least an estimate.

Relatedly, is simdjson expected to slow the frequencies of the cores it's running on? For example, running AVX512 code will slow the core. I don't know if simdjson uses AVX512 yet, but I believe there were similar slowdowns with AVX and/or AVX2, at least on certain CPU generations. I don't remember the details. In any case, does simdjson slow down the core(s) on certain CPU families?

**Comment by lemire** [comment]
@JoeUX 

> Estimated parsing speed isn't super useful without knowing the cost in CPU and memory, especially since I'd use it on-the-fly on a server handling various other chores.

The parsing speed *is* the CPU cost. In a single-threaded context, the faster your function runs, the less CPU it uses.

> I expect simdjson to have fairly light overhead, but this is not mentioned or reported anywhere as far as I can see. I think it's pretty important for a lot of people to know the overhead, at least an estimate.

In simdjson, we are careful about memory usage and designed with a server scenario where one does not want do allocations as a matter of course. It is designed so that you can parse terabytes of JSON files with kilobytes of memory, because it is centered around the reuse of the same `parser` instance, as described in the documentation.

As for measurement... Memory is a complex topic. Virtual memory is not actual memory and gets translated into RAM usage by the OS, memory gets allocated in pages and pages come in difference sizes, and so forth. I don't think it can be determined in a system-independent manner. However, we certainly invite benchmarks and analysis.

> Relatedly, is simdjson expected to slow the frequencies of the cores it's running on? For example, running AVX512 code will slow the core. I don't know if simdjson uses AVX512 yet, but I believe there were similar slowdowns with AVX and/or AVX2, at least on certain CPU generations. I don't remember the details. In any case, does simdjson slow down the core(s) on certain CPU families?

We do not yet support AVX512. There are no AVX2 heavy instructions requiring a higher license. And you can select the kernel you prefer (e.g., run just SSE).

---

I am going to close this issue. 

We have extensive documentation regarding our performance results starting from a [journal article at a top journal (VLDB, 2019)](https://arxiv.org/abs/1902.08318), multiple benchmarks and so forth.

We do invite further benchmarks and analysis... and we can always do better... but we are probably the JSON parsing library with the most obsessively thoroughly documented performance.
