### ISSUE TITLE
Check for 32-bit MinGW to Permit R Distribution on Windows

### ISSUE THREAD

**Issue by knapply** [simdjson/simdjson#976]
Following up on https://github.com/eddelbuettel/rcppsimdjson/issues/24#issuecomment-648924662 and https://github.com/eddelbuettel/rcppsimdjson/issues/14#issue-623738180

**Is your feature request related to a problem? Please describe.**

More limitation than problem. We'd like to make [`RcppSimdJson`](https://github.com/eddelbuettel/rcppsimdjson) available to Windows users on CRAN (R's de-facto package clearing house). In order to do so, the package unfortunately needs to be able to build on 32-bit Windows systems. 

**Describe the solution you'd like**

In the solution I've tested, `simdjson` checks

```
#if (defined(SIMDJSON_REGULAR_VISUAL_STUDIO) || (defined(__MINGW32__) && (!defined(__MINGW64__)))
```

instead of only checking `#ifdef SIMDJSON_REGULAR_VISUAL_STUDIO` in the following locations:

https://github.com/simdjson/simdjson/blob/e01f1434fb15218208d98ff6fef93d3a4bad349d/singleheader/simdjson.h#L99-L111

https://github.com/simdjson/simdjson/blob/e01f1434fb15218208d98ff6fef93d3a4bad349d/singleheader/simdjson.cpp#L937-L938

https://github.com/simdjson/simdjson/blob/e01f1434fb15218208d98ff6fef93d3a4bad349d/singleheader/simdjson.cpp#L958

https://github.com/simdjson/simdjson/blob/e01f1434fb15218208d98ff6fef93d3a4bad349d/singleheader/simdjson.cpp#L11117

**Describe alternatives you've considered**

* setting `#define SIMDJSON_REGULAR_VISUAL_STUDIO 1` on our end
  + this isn't an option as it enables other Visual Studio specific behaviors.
* to quote @eddelbuettel , wrapping everything on our end in `#ifndef DEADMEAT` to basically kill compilation (passing checks is easy if it doesn't do anything)

**Additional context**

I suspect there are other considerations that need to be made for downstream projects.

**Are you willing to contribute code or documentation toward this new feature?**

I am. The solution I put together used the amalgamated files, so I will need to walk through their sources first.

Before I do that, it would be good to know if there are immediate objections to the solution I'm proposing.

**Comment by lemire** [comment]
@knapply 

Can't we just add the following...

```C++
#if (defined(__MINGW32__) && (!defined(__MINGW64__)))
#define SIMDJSON_REGULAR_VISUAL_STUDIO
#endif 
```

You write...

> setting #define SIMDJSON_REGULAR_VISUAL_STUDIO 1 on our end: this isn't an option as it enables other Visual Studio specific behaviors.


Can you elaborate? Do you mean that it does not build or are you concerned about something else ?



Do you happen to know how to setup testing for MINGW32 under something like appveyor, because we can't support what we can't test systematically.

**Comment by knapply** [comment]
MinGW ports GCC compilers, meaning it compiles C++ using g++. It doesn't know anything about all the Visual Studio-specific things that `SIMDJSON_REGULAR_VISUAL_STUDIO` enables.

That said, I found another way. Rather than focus on MinGW, maybe just thinking of it as GCC would be more palatable.


This is the first roadblock (1.) ....

https://github.com/simdjson/simdjson/blob/5fa9faca20b57667bb41379a54e9b7ee32cf355c/include/simdjson/portability.h#L45-L57

... so at the moment, `simdjson` won't compile 32-bit for anything but Visual Studio.


1.  If line 46 is changed from this...

https://github.com/simdjson/simdjson/blob/5fa9faca20b57667bb41379a54e9b7ee32cf355c/include/simdjson/portability.h#L46

... to `#if defined(SIMDJSON_REGULAR_VISUAL_STUDIO) || defined(__GNUC__)`

... we're through the first gate.

2. Then if this piece changes from...

https://github.com/simdjson/simdjson/blob/603b6596af1b040c2c078e5b52169f009461a4ff/src/jsoncharutils.h#L320-L321

... to just `#if !defined(_M_X64) && !defined(_M_ARM64)`


3. and these lines...

https://github.com/simdjson/simdjson/blob/2a1f8fa8f16d3ef5bc32ae8fe3cc105f6a3e0fba/src/haswell/bitmanipulation.h#L61

https://github.com/simdjson/simdjson/blob/2a1f8fa8f16d3ef5bc32ae8fe3cc105f6a3e0fba/src/westmere/bitmanipulation.h#L69

... change to  `#if !defined(_M_X64) && !defined(_M_ARM64)` (I can only confirm for westmere at the moment) we're all set. 

With those changes, we pass on 32-bit Windows using the toolchain we're held to. 

Does that seem like a reasonable route? Am I missing any traps?

**Comment by lemire** [comment]
At a glance, none of what you suggest appears terribly dangerous. But I am concerned with

```
#if !defined(_M_X64) && !defined(_M_ARM64)
```

It is messy to spread this around and could be nasty to debug. I know I wrote it, but I have paired it with SIMDJSON_REGULAR_VISUAL_STUDIO and so I know pretty much when it fires... It is easy for me to reason about it.

If we want to generalize... Well...

Here is something that might be better...

We have...

```
#if defined(__x86_64__) || defined(_M_AMD64)
#define SIMDJSON_IS_X86_64 1
#endif
#if defined(__aarch64__) || defined(_M_ARM64)
#define SIMDJSON_IS_ARM64 1
#endif
```

We could have...

```
#if defined(__x86_64__) || defined(_M_AMD64)
#define SIMDJSON_IS_X86_64 1
#elif defined(__aarch64__) || defined(_M_ARM64)
#define SIMDJSON_IS_ARM64 1
#else 
#define SIMDJSON_IS_NOT_64BITS 1
#endif
```

And then everywhere you can do

```
#if SIMDJSON_IS_NOT_64BITS
```

instead of the ugly and less safe...

```
#if (!defined(_M_X64) && !defined(_M_ARM64))
```

And something like


```
 #if defined(SIMDJSON_REGULAR_VISUAL_STUDIO) &&  defined(SIMDJSON_IS_NOT_64BITS)
```

is a lot easier to read and debug.

Now, maybe we can do better and use `SIMDJSON_IS_32BITS` but you get the idea.



Note also that instead of "defined(...)", we can just do "#if SIMDJSON_IS_NOT_64BITS" because when it is defined, it is always 1 (true). And when it is undefined, it evaluate to false.

But you see my point.

**Comment by knapply** [comment]
Agreed, that is much nicer! 

Would you like me to take a stab at this? Or do you feel it's safer to tackle internally?

**Comment by lemire** [comment]
Why don't you issue a PR. It simple enough that it should be uncontroversial and it will take me longer to re-engineer it than for you to write it. You'll get credit. And you'll be able to check that it does solve the issue.

I *would* feel better if we could add 32-bit CI tests.

**Comment by knapply** [comment]
Sounds good. I'll give it a go.

> I would feel better if we could add 32-bit CI tests.

... and work on that in the process.

**Comment by lemire** [comment]
@knapply I am thinking about releasing a patch release (0.4.1). Do you think you could issue the PR soon-ish so that we can squeeze it into 0.4.1?

There is no rush on my end, it is just a matter of planning.

**Comment by eddelbuettel** [comment]
FWIW I cut 0.0.6 off your 0.4.0 and that is now on CRAN, but we can easily follow up with 0.0.7, or call it 0.1.0 if it gets us Windoze.

**Comment by knapply** [comment]
PR issued, but I haven't had a moment to sort out 32-bit CI tests.

**Comment by lemire** [comment]
Issue resolved. We now test systematically under x86 (32-bit) using both clang and gcc.

I'd very much like to have wingw32 tests, if someone wants to contribute that.

It is part of version 0.4.1, just released.

**Comment by knapply** [comment]
Thank you @lemire .

Still working on a mingw test solution, but getting everything to align is proving tricky.

**Comment by lemire** [comment]
In theory, appveyor supports it, but there is not a lot of documentation, and there is no remote access... I can't figure out why they just don't offer examples. Maybe like of staffing.

**Comment by knapply** [comment]
I've made triple-digit attempts over a few forks to get things to cooperate on appveyor, circleci, drone, or GH actions and am out of ideas. I'm coming up short on finding relevant documentation or examples. 

This is probably the closest I've gotten: https://github.com/knapply/simdjson/runs/814434181?check_suite_focus=true
w/ this workflow file: https://github.com/knapply/simdjson/actions/runs/149890622/workflow

**Comment by lemire** [comment]
@knapply Your "closest" looks good to me with the caveat that we do not appear to build under mingw.

We have this...

```
../tests/parse_many_test.cpp: In function 'bool validate(const char*)':
188
../tests/parse_many_test.cpp:41:52: error: 'alphasort' was not declared in this scope
189
     int c = scandir(dirname, &entry_list, nullptr, alphasort);
190
                                                    ^~~~~~~~~
191
../tests/parse_many_test.cpp:41:13: error: 'scandir' was not declared in this scope
192
     int c = scandir(dirname, &entry_list, nullptr, alphasort);
193
             ^~~~~~~
194
../tests/parse_many_test.cpp:41:13: note: suggested alternative: 'srand'
195
     int c = scandir(dirname, &entry_list, nullptr, alphasort);
196
             ^~~~~~~
197
             srand
198

```


I bet that the problem starts there...

https://github.com/simdjson/simdjson/blob/9842e1f9d019e89f986ce738493316fe848d7e04/windows/dirent_portable.h

**Comment by knapply** [comment]
I assumed I was still not configuring the test machine correctly as I can build RcppSimdJson on Windows using mingw...

![image](https://user-images.githubusercontent.com/26281249/85958106-ba70e980-b947-11ea-8ad8-bde274849ed8.png)

Do you suspect I would not hit those errors without running the test suite?

**Comment by eddelbuettel** [comment]
I am missing something here @knapply .  You running `R CMD INSTALL ....` (or equivalent) does in no way shape or form depend on tests passing.  Are you saying it is?  Sorry to be bearer of bad news.  _You_ as your local admin are free to install whatever.

What CRAN takes is different.  Or, more generally, what we bother to share with others has these higher limits. So what you say does not disprove or answer what @lemire is raising.  Or maybe I am missing something.  I am on ice tea rather than coffee...

**Comment by knapply** [comment]
> Are you saying it is?

My question implied the exact opposite. 😕


@lemire It looks like "dirent_portable.h" doesn't make it into `singleheader/` and is only included in during tests. I'll see if it can be installed using Scoop like was done for Ninja.

**Comment by lemire** [comment]
@knapply No, it is not part of  the simdjson library and shouldn't be. 

@eddelbuettel The problems here are not part of the simdjson library.

**Comment by knapply** [comment]
Not for lack of [trying](https://github.com/knapply/simdjson/commits/knapply/mingw-ci), but it's still not resolved. 

The first hurdle seems to be tricking inclusion of `windows/toni_ronnko_dirent.h` without including everything else in `/windows`, but even when it's bypassed I'll encounter failures running `singleheader/amalgamation.sh` and beyond.

**Comment by lemire** [comment]
I have been working on a PR based on your work. 

I have encountered probably the same problems, but I did not fix everything.

It does not look to me like mingw is a simple port of GCC/libs to Windows. The standard library it comes with is not the same at all.

**Comment by eddelbuettel** [comment]
> The standard library it comes with is not the same at all.

It is a fairly new toolchain in R-land. It was added less than two months ago (after considerable work). We can speak to @jeroen who lead this.  I can however assure you that the previous one, based on g++-4.9.3, was clearly worse because I once had a friend help me by backporting `strptime` (from clang's library) for use in my RcppCCTZ package:

```
2017-01-07  Daniel C. Dillon  <dcdillon@gmail.com>

	* inst/include/get_time.h: Ported from C++ library to fill in for the
	missing strptime on Windows with g++ 4.* as used by Rtools
	* src/time_zone_format.cc: Use ported routine
	* src/examples.cpp: Use Windows format strings on Windows

```

**Comment by lemire** [comment]
@eddelbuettel I am confident I can fix the remaining problem, I just need to install the toolchain on a machine here. I expect that the trouble has to do with file access. Without @knapply, I would not even have been trying, but I am now relatively confident I can fix this.

**Comment by eddelbuettel** [comment]
I really _really_ appreciate the hard work you two put into this.

**Comment by knapply** [comment]
@lemire It looks like you suspect Scoop is the issue.

I pulled down your recent c++ changes and started and started trying Chocolatey instead of Scoop in the workflow file. Chocolatey turns out to be pre-loaded and I was able to build and pass tests locally using it.

https://github.com/knapply/simdjson/actions/runs/152034409/workflow

[This is where I'm seeing 64-bit lock up up](https://github.com/knapply/simdjson/runs/820300865?check_suite_focus=true). 

![image](https://user-images.githubusercontent.com/26281249/86063489-db0c7280-ba1f-11ea-80ff-c09ef5ca8d88.png)

I haven't sorted out the magical incantations for 32-bit (switching seems to be a Ninja switch), but it turns out MinGW is built into the image as well. I've can install a 32-bit version with `choco install -y mingw -x86 --force`, but it breaks the path and I haven't sorted out how to fix it after. It's extremely frustrating.

**Comment by lemire** [comment]
@eddelbuettel 

Please see version 0.4.3. We are now testing in CI MinGW.

**Comment by lemire** [comment]
>  It looks like you suspect Scoop is the issue.

Scoop is fine. It just took me forever to figure out that you have to install the 32-bit version, then uninstall it, the install the 64-bit and so forth. I naively expected a universal version. But it is not scoop's fault. 

Scoop is good. I like it. I am sure that there are other alternatives, but it did not give me trouble... 


MinGW has bugs though. The inttypes header is not standard compliant...  the pow function... oh my! In my tests, I got large deviations (several ULP) from the correct values. It matters because we compare against it. I feared that we had a bug... but it turns out that we got the correct values... it is the pow function that it incorrect (just under MinGW).


> I hope you're not as frustrated as I am, but thank you for continuing to investigate.

It is *super* frustrating mostly because all of this stuff is badly documented.

>  it turns out MinGW is built into the image as well

I don't think you can have both the 32-bit and the 64-bit version at the same time. Not with scoop at least.

Now that I have figured out caches, it does not matter because I just load up my configuration from cache and I am all set.


*However* GitHub actions appear to go dead easily. So we don't run all tests. The basictests are rather intense, with long loops... it tends just hang in there... never finishing. I think it is bad. They don't timeout, as I thought initially (which would be acceptable). They just hang. That's bad.

It is still good enough for me. I cannot do deep tests, but we don't need deep tests with all platforms.

**Comment by lemire** [comment]
On the plus side... the GCC builds are very fast...

<img width="2505" alt="Screen Shot 2020-06-29 at 9 35 33 PM" src="https://user-images.githubusercontent.com/391987/86072822-833a2f80-ba50-11ea-8b50-cf55af6e24d6.png">

**Comment by knapply** [comment]
> It is super frustrating mostly because all of this stuff is badly documented.

It looks like it could've been something like this the whole time... 🤦‍♂️

https://github.com/knapply/simdjson/runs/820896689?check_suite_focus=true#step:4:1185

I know it's late to the party, so I'll just leave it here for safekeeping.

```yml
name: MinGW-CI

on: push

jobs:
  windows-mingw:
    name: ${{ matrix.mingw }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mingw: ["MINGW32", "MINGW64"]
    env:
      CMAKE_GENERATOR: MSYS Makefiles

    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v1
        with:
          update: true # cache: true
          msystem: ${{ matrix.mingw }}
      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake -DSIMDJSON_BUILD_STATIC=ON -DSIMDJSON_DO_NOT_USE_THREADS_NO_MATTER_WHAT=ON ..
          cmake --build . --verbose
          ctest -j4 --output-on-failure -E checkperf
```

**Comment by jeroen** [comment]
Note that R compiles 32-bit (mingw32) with `-msse2 -mfpmath=sse -mstackrealign` in order to get matching results with 64-bit (mingw64).

The main difference in float precision between i686 and x86_64 could come from whether it uses x87 (with 80 bit floats as
intermediates, as long as all intermediates are stored in registers). As explained in https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/x86-Options.html#x86-Options the `-mfpmath=sse` is the default for x86-64 but not for i686.

**Comment by lemire** [comment]
@knapply

This is simpler but I like the scoop approach because it is easy for me to reproduce it locally on any machine. Your simpler script makes assumption regarding the host.

As long as scoop is maintained and available, the current testing scripts are going to work very nicely. :-)
